import streamlit as st
import random

# Tự tạo danh sách từ vựng trực tiếp trong file để không bị lỗi kết nối file khác
VOCAB_LIST = [
    (1, "assignment", "n", "/əˈsaɪn.mənt/", "bài tập tiểu luận"),
    (2, "attentive", "adj", "/əˈten.tɪv/", "chăm chú, chú ý"),
    (3, "admission", "n", "/ədˈmɪʃ.ən/", "sự nhận vào, cho vào"),
    (4, "curriculum", "n", "/kəˈrɪk.jə.ləm/", "chương trình học"),
    (5, "discipline", "n", "/ˈdɪs.ə.plɪn/", "kỷ luật"),
    (6, "coursework", "n", "/ˈkɔːrs.wɝːk/", "đồ án môn học", "Giáo dục"),
        (7, "curriculum", "n", "/kəˈrɪk.jə.ləm/", "chương trình giảng dạy", "Giáo dục"),
        (8, "distance learning", "n", "/ˈdɪs.təns ˌlɝː.nɪŋ/", "việc học từ xa, học trực tuyến", "Giáo dục"),
        (9, "eager beaver", "n", "/ˌiː.ɡɚ ˈbiː.vɚ/", "người chăm chỉ, tham việc", "Giáo dục"),
        (10, "enroll", "v", "/ɪnˈrəʊl/", "đăng ký", "Giáo dục"),
        (11, "evaluation", "n", "/ɪˌvæl.juˈeɪ.ʃən/", "sự đánh giá", "Giáo dục"),
        (12, "fellowship", "n", "/ˈfel.oʊ.ʃɪp/", "đội nhóm; học bổng nghiên cứu sinh", "Giáo dục"),
        (13, "final (exam)", "n", "/ˈfɑɪ·nəl (iɡˈzæm)/", "bài thi cuối kỳ", "Giáo dục"),
        (14, "graduate", "v", "/ˈɡrædʒ.u.ət/", "tốt nghiệp, ra trường", "Giáo dục"),
        (15, "higher education", "n", "/ˌhaɪ.ɚ ed.jʊˈkeɪ.ʃən/", "giáo dục cấp đại học", "Giáo dục"),
        (16, "illiterate", "n", "/ɪˈlɪt̬.ɚ.ət/", "mù chữ, thất học", "Giáo dục"),
        (17, "institution", "n", "/ˌɪn.stəˈtuː.ʃən/", "viện, cơ quan", "Giáo dục"),
        (18, "internship", "n", "/ˈɪn.tɝːn.ʃɪp/", "kỳ thực tập", "Giáo dục"),
        (19, "kindergarten", "n", "/ˈkɪn.dɚˌɡɑːr.tən/", "lớp mẫu giáo, nhà trẻ", "Giáo dục"),
        (20, "lecture", "n", "/ˈlek.tʃɚ/", "bài giảng, bài diễn thuyết", "Giáo dục"),
        (21, "literacy", "n", "/ˈlɪt̬.ɚ.ə.si/", "khả năng biết đọc và viết", "Giáo dục"),
        (22, "material", "n", "/məˈtɪr.i.əl/", "học liệu", "Giáo dục"),
        (23, "physical education", "n", "/ˌfɪz.ɪ.kəl ed.jʊˈkeɪ. ʃən/", "giáo dục thể chất", "Giáo dục"),
        (24, "plagiarize", "v", "/ˈpleɪ.dʒə.raɪz/", "đạo văn, sao chép", "Giáo dục"),
        (25, "practice", "n", "/ˈpræk.tɪs/", "bài luyện tập", "Giáo dục"),
        (26, "premise", "n", "/ˈprem.ɪs/", "giả thuyết, tiền đề", "Giáo dục"),
        (27, "preschool", "n, adj", "/ˈpriː.skuːl/", "trường mầm non", "Giáo dục"),
        (28, "primary school", "n", "/ˈpraɪ.mɚ.i ˌskuːl/", "trường tiểu học, trường cấp 1", "Giáo dục"),
        (29, "private school", "n", "/ˌpraɪ.vət ˈskuːl/", "trường tư", "Giáo dục"),
        (30, "qualification", "n", "/ˌkwɑː.lə.fəˈkeɪ.ʃən/", "năng lực, trình độ chuyên môn", "Giáo dục"),
        (31, "secondary school", "n", "/ˈsek.ən.der.i ˌskuːl/", "trường trung học, trường cấp 2", "Giáo dục"),
        (32, "syllabus", "n", "/ˈsɪl.ə.bəs/", "giáo trình", "Giáo dục"),
        (33, "teacher's pet", "n", "/ˌtiː.tʃɚz ˈpet/", "học sinh cưng của giáo viên", "Giáo dục"),
        (34, "thesis", "n", "/ˈθiː.sɪs/", "luận văn, luận án", "Giáo dục"),
        (35, "tuition", "n", "/tuːˈɪʃ.ən/", "hoạt động giảng dạy, hướng dẫn", "Giáo dục"),
        (36, "undergraduate", "n", "/ˌʌn.dɚˈɡrædʒ.u.ət/", "sinh viên chưa tốt nghiệp", "Giáo dục"),
        (37, "vocational school", "n", "/voʊˈkeɪ.ʃən.əl ˌskuːl/", "trường dạy nghề", "Giáo dục"),
    
        # CHỦ ĐỀ 2: SCHOOL OBJECTS - ĐỒ DÙNG HỌC TẬP (38 - 66)
        (38, "backpack", "n", "/ˈbæk.pæk/", "ba lô, cặp đeo sau lưng", "Đồ dùng học tập"),
        (39, "ballpoint pen", "n", "/ˌbɑːl.pɔɪnt ˈpen/", "bút bi", "Đồ dùng học tập"),
        (40, "beaker", "n", "/ˈbiː.kɚ/", "cốc đong trong phòng thí nghiệm", "Đồ dùng học tập"),
        (41, "binder", "n", "/ˈbaɪn.dɚ/", "bìa rời", "Đồ dùng học tập"),
        (42, "blackboard", "n", "/ˈblæk.bɔːrd/", "bảng đen", "Đồ dùng học tập"),
        (43, "book", "n", "/bʊk/", "quyển sách", "Đồ dùng học tập"),
        (44, "calculator", "n", "/ˈkæl.kjə.leɪ.t̬ɚ/", "máy tính bỏ túi", "Đồ dùng học tập"),
        (45, "chair", "n", "/tʃer/", "ghế", "Đồ dùng học tập"),
        (46, "clip", "n", "/klɪp/", "kẹp ghim", "Đồ dùng học tập"),
        (47, "clock", "n", "/klɑːk/", "đồng hồ", "Đồ dùng học tập"),
        (48, "compass", "n", "/ˈkʌm.pəs/", "la bàn", "Đồ dùng học tập"),
        (49, "computer", "n", "/kəmˈpjuː.t̬ɚ/", "máy tính để bàn", "Đồ dùng học tập"),
        (50, "desk", "n", "/desk/", "bàn học", "Đồ dùng học tập"),
        (51, "eraser", "n", "/ɪˈreɪ.sɚ/", "tẩy, gôm", "Đồ dùng học tập"),
        (52, "funnel", "n", "/ˈfʌn.əl/", "phễu", "Đồ dùng học tập"),
        (53, "globe", "n", "/ɡloʊb/", "quả địa cầu", "Đồ dùng học tập"),
        (54, "glue", "n", "/ɡluː/", "keo hồ", "Đồ dùng học tập"),
        (55, "highlighter", "n", "/ˈhaɪˌlaɪ.t̬ɚ/", "bút nhớ", "Đồ dùng học tập"),
        (56, "magnifying glass", "n", "/ˈmæɡ.nə.faɪ.ɪŋ ˌɡlæs/", "kính lúp", "Đồ dùng học tập"),
        (57, "map", "n", "/mæp/", "bản đồ", "Đồ dùng học tập"),
        (58, "paint brush", "n", "/ˌbrɑːd ˈbrʌʃ/", "cọ tô màu", "Đồ dùng học tập"),
        (59, "paper", "n", "/ˈpeɪ.pɚ/", "giấy", "Đồ dùng học tập"),
        (60, "pin", "n", "/pɪn/", "đinh ghim", "Đồ dùng học tập"),
        (61, "protractor", "n", "/prəˈtræk.tɚ/", "thước đo góc", "Đồ dùng học tập"),
        (62, "scissors", "n", "/ˈsɪz.ɚz/", "kéo", "Đồ dùng học tập"),
        (63, "scotch tape", "n", "/ˌskɑːtʃ ˈteɪp/", "băng keo", "Đồ dùng học tập"),
        (64, "set square", "n", "/ˈset ˌskwer/", "thước vuông, ê-ke", "Đồ dùng học tập"),
        (65, "stapler", "n", "/ˈsteɪ.plɚ/", "cái dập ghim", "Đồ dùng học tập"),
        (66, "test tube", "n", "/ˈtest ˌtuːb/", "ống thí nghiệm", "Đồ dùng học tập"),
    
        # CHỦ ĐỀ 3: NATURE - THIÊN NHIÊN (67 - 130)
        (67, "animal", "n", "/ˈæn.ɪ.məl/", "động vật, thú vật", "Thiên nhiên"),
        (68, "Arctic", "n, adj", "/ˈɑːrk.tɪk/", "vùng Bắc Cực; (thuộc) Bắc Cực", "Thiên nhiên"),
        (69, "atmosphere", "n", "/ˈæt.mə.sfɪr/", "khí quyển", "Thiên nhiên"),
        (70, "beach", "n", "/biːtʃ/", "bãi biển", "Thiên nhiên"),
        (71, "breezy", "adj", "/ˈbriː.zi/", "gió thổi hiu mát", "Thiên nhiên"),
        (72, "bush", "n", "/bʊʃ/", "bụi cây, bụi rậm", "Thiên nhiên"),
        (73, "cave", "n", "/keɪv/", "hang động", "Thiên nhiên"),
        (74, "cliff", "n", "/klɪf/", "vách đá", "Thiên nhiên"),
        (75, "coal", "n", "/koʊl/", "than đá", "Thiên nhiên"),
        (76, "creek", "n", "/kriːk/", "lạch, nhánh sông, sông con", "Thiên nhiên"),
        (77, "daisy", "n", "/ˈdeɪ.zi/", "hoa cúc", "Thiên nhiên"),
        (78, "deforestation", "n", "/diːˌfɔːr.əˈsteɪ.ʃən/", "sự tàn phá rừng", "Thiên nhiên"),
        (79, "desert", "n", "/ˈdez.ɚt/", "sa mạc, hoang mạc", "Thiên nhiên"),
        (80, "ecological", "adj", "/ˌiː.kəˈlɑː.dʒɪ.kəl/", "(thuộc) sinh thái", "Thiên nhiên"),
        (81, "environment", "n", "/ɪnˈvaɪ.rən.mənt/", "môi trường", "Thiên nhiên"),
        (82, "eruption", "n", "/ɪˈrʌp.ʃən/", "sự phun trào (núi lửa)", "Thiên nhiên"),
        (83, "flood", "n", "/flʌd/", "lũ lụt", "Thiên nhiên"),
        (84, "flower", "n", "/ˈflaʊ.ɚ/", "hoa", "Thiên nhiên"),
        (85, "fossil", "n, adj", "/ˈfɑː.səl/", "chất liệu hóa thạch; hóa thạch, hóa đá", "Thiên nhiên"),
        (86, "gloomy", "adj", "/ˈɡluː.mi/", "u ám, ảm đạm", "Thiên nhiên"),
        (87, "graze", "v", "/ɡreɪz/", "thả (súc vật) ăn cỏ", "Thiên nhiên"),
        (88, "herd", "n", "/hɝːd/", "bầy, đàn (vật nuôi)", "Thiên nhiên"),
        (89, "highland", "n", "/ˈhaɪ.lənd/", "cao nguyên", "Thiên nhiên"),
        (90, "hurricane", "n", "/ˈhɝː.ɪ.keɪn/", "bão", "Thiên nhiên"),
        (91, "insect", "n", "/ˈɪn.sekt/", "côn trùng, sâu bọ", "Thiên nhiên"),
        (92, "livestock", "n", "/ˈlaɪv.stɑːk/", "vật nuôi, thú nuôi", "Thiên nhiên"),
        (93, "meadow", "n", "/ˈmed.oʊ/", "đồng cỏ, bãi cỏ", "Thiên nhiên"),
        (94, "misty", "adj", "misty", "có sương mù", "Thiên nhiên"),
        (95, "mountain", "n", "/ˈmaʊn.tən/", "núi, dãy núi", "Thiên nhiên"),
        (96, "mud", "n", "/mʌd/", "bùn", "Thiên nhiên"),
        (97, "overcast", "v, adj", "/ˈoʊ.vɚ.kæst/", "mây phủ; tối sầm do mây phủ", "Thiên nhiên"),
        (98, "peninsula", "n", "/pəˈnɪn.sə.lə/", "bán đảo", "Thiên nhiên"),
        (99, "petal", "n", "/ˈpet̬.əl/", "cánh hoa", "Thiên nhiên"),
        (100, "planet", "n", "/ˈplæn.ɪt/", "hành tinh", "Thiên nhiên"),
        (101, "pollution", "n", "/pəˈluː.ʃən/", "ô nhiễm", "Thiên nhiên"),
        (102, "pond", "n", "/pɑːnd/", "ao nước", "Thiên nhiên"),
        (103, "river", "n", "/ˈrɪv.ɚ/", "dòng sông", "Thiên nhiên"),
        (104, "riverbank", "n", "/ˈrɪvəˌbæŋk/", "bờ sông, bãi sông, vùng đất ven sông", "Thiên nhiên"),
        (105, "root", "n", "/ruːt/", "gốc, rễ cây", "Thiên nhiên"),
        (106, "rubbish", "n", "/ˈrʌb.ɪʃ/", "rác rưởi", "Thiên nhiên"),
        (107, "savanna", "n", "/səˈvæn.ə/", "hoang mạc, thảo nguyên", "Thiên nhiên"),
        (108, "scenery", "n", "/ˈsiː.nɚ.i/", "phong cảnh, cảnh vật", "Thiên nhiên"),
        (109, "sea", "n", "/siː/", "biển", "Thiên nhiên"),
        (110, "season", "n", "/ˈsiː.zən/", "mùa trong năm", "Thiên nhiên"),
        (111, "seed", "n", "/siːd/", "hạt giống", "Thiên nhiên"),
        (112, "slaughter", "n, v", "/ˈslɑː.t̬ɚ/", "sự giết mổ; giết mổ thịt", "Thiên nhiên"),
        (113, "sleet", "n, v", "/sliːt/", "mưa tuyết, mưa đá; trời mưa tuyết", "Thiên nhiên"),
        (114, "slope", "n", "/sloʊp/", "dốc", "Thiên nhiên"),
        (115, "snowslide", "n", "/ˈsnōˌslīd/", "tuyết lở", "Thiên nhiên"),
        (116, "soil", "n", "/sɔɪl/", "đất trồng, đất dai", "Thiên nhiên"),
        (117, "solar", "adj", "/ˈsoʊ.lɚ/", "(thuộc) mặt trời", "Thiên nhiên"),
        (118, "sunshine", "n", "/ˈsʌn.ʃaɪn/", "ánh sáng mặt trời, ánh nắng", "Thiên nhiên"),
        (119, "sustainable", "adj", "/səˈsteɪ.nə.bəl/", "bền vững", "Thiên nhiên"),
        (120, "temperature", "n", "/ˈtem.pɚ.ə.tʃɚ/", "nhiệt độ", "Thiên nhiên"),
        (121, "tornado", "n", "/tɔːrˈneɪ.doʊ/", "lốc xoáy", "Thiên nhiên"),
        (122, "tsunami", "n", "/tsuːˈnɑː.mi/", "sóng thần", "Thiên nhiên"),
        (123, "valley", "n", "/ˈvæl.i/", "thung lũng, châu thổ, lưu vực", "Thiên nhiên"),
        (124, "vapor", "v", "/ˈveɪ.pər/", "bốc hơi", "Thiên nhiên"),
        (125, "vivid", "adj", "/ˈvɪv.ɪd/", "sống động, mãnh liệt", "Thiên nhiên"),
        (126, "volcano", "n", "/vɑːlˈkeɪ.noʊ/", "núi lửa", "Thiên nhiên"),
        (127, "waterfall", "n", "/ˈwɑː.t̬ɚ.fɑːl/", "thác nước", "Thiên nhiên"),
        (128, "wild", "n, adj", "/waɪld/", "thiên nhiên hoang dại; hoang dại", "Thiên nhiên"),
        (129, "wildlife", "n", "/ˈwaɪld.laɪf/", "sinh vật hoang dã, thiên nhiên hoang dã", "Thiên nhiên"),
        (130, "winter", "n", "/ˈwɪn.t̬ɚ/", "mùa đông", "Thiên nhiên"),
    
        # CHỦ ĐỀ 4: ANIMALS - ĐỘNG VẬT (131 - 191)
        (131, "bald eagle", "n", "/ˌbɑːld ˈiː.ɡəl/", "đại bàng trắng", "Động vật"),
        (132, "bee", "n", "/biː/", "con ong", "Động vật"),
        (133, "blackbird", "n", "/ˈblæk.bɝːd/", "chim két", "Động vật"),
        (134, "cat", "n", "/kæt/", "con mèo", "Động vật"),
        (135, "chicken", "n", "/ˈtʃɪk.ɪn/", "con gà", "Động vật"),
        (136, "chimpanzee", "n", "/ˌtʃɪm.pænˈziː/", "con tinh tinh", "Động vật"),
        (137, "cow", "n", "/kaʊ/", "con bò", "Động vật"),
        (138, "coyote", "n", "/kaɪˈoʊ.t̬i/", "chó sói đồng cỏ", "Động vật"),
        (139, "crab", "n", "/kræb/", "con cua", "Động vật"),
        (140, "crow", "n", "/kroʊ/", "(một loại) quạ", "Động vật"),
        (141, "deer", "n", "/dɪr/", "con hươu, nai", "Động vật"),
        (142, "dog", "n", "/dɑːɡ/", "con chó", "Động vật"),
        (143, "dove", "n", "/dʌv/", "chim bồ câu", "Động vật"),
        (144, "duck", "n", "/dʌk/", "con vịt", "Động vật"),
        (145, "elephant", "n", "/ˈel.ə.fənt/", "con voi", "Động vật"),
        (146, "fish", "n", "/fɪʃ/", "con cá", "Động vật"),
        (147, "flamingo", "n", "/fləˈmɪŋ.ɡoʊ/", "chim hồng hạc", "Động vật"),
        (148, "fox", "n", "/fɑːks/", "con cáo", "Động vật"),
        (149, "giraffe", "n", "/dʒɪˈræf/", "hươu cao cổ", "Động vật"),
        (150, "goat", "n", "/ɡoʊt/", "con dê", "Động vật"),
        (151, "goldfish", "n", "/ˈɡoʊld.fɪʃ/", "cá vàng", "Động vật"),
        (152, "goose", "n", "/ɡuːs/", "con ngỗng", "Động vật"),
        (153, "hamster", "n", "/ˈhæm.stɚ/", "chuột đồng", "Động vật"),
        (154, "hawk", "n", "/hɑːk/", "chim diều hâu", "Động vật"),
        (155, "hedgehog", "n", "/ˈhedʒ.hɑːɡ/", "con nhím", "Động vật"),
        (156, "hippopotamus", "n", "/ˌhɪp.əˈpɑː.t̬ə.məs/", "hà mã", "Động vật"),
        (157, "horse", "n", "/hɔːrs/", "con ngựa", "Động vật"),
        (158, "kangaroo", "n", "/ˌkæŋ.ɡəˈruː/", "chuột túi", "Động vật"),
        (159, "kitten", "n", "/ˈkɪt̬.ən/", "mèo con", "Động vật"),
        (160, "koala", "n", "/koʊˈɑː.lə/", "gấu túi", "Động vật"),
        (161, "leopard", "n", "/ˈlep.ɚd/", "con báo", "Động vật"),
        (162, "lion", "n", "/ˈlaɪ.ən/", "sư tử", "Động vật"),
        (163, "mole", "n", "/moʊl/", "chuột chũi", "Động vật"),
        (164, "monkey", "n", "/ˈmʌŋ.ki/", "con khỉ", "Động vật"),
        (165, "mouse", "n", "/maʊs/", "con chuột", "Động vật"),
        (166, "ostrich", "n", "/ˈɑː.strɪtʃ/", "đà điểu", "Động vật"),
        (167, "otter", "n", "/ˈɑː.t̬ɚ/", "rái cá", "Động vật"),
        (168, "owl", "n", "/aʊl/", "con cú", "Động vật"),
        (169, "ox", "n", "/ɑːks/", "con bò đực", "Động vật"),
        (170, "panda", "n", "/ˈpæn.də/", "gấu trúc", "Động vật"),
        (171, "parrot", "n", "/ˈper.ət/", "con vẹt", "Động vật"),
        (172, "peacock", "n", "/ˈpiː.kɑːk/", "con công", "Động vật"),
        (173, "penguin", "n", "/ˈpeŋ.ɡwɪn/", "chim cánh cụt", "Động vật"),
        (174, "pig", "n", "/pɪɡ/", "con lợn, heo", "Động vật"),
        (175, "pigeon", "n", "/ˈpɪdʒ.ən/", "chim bồ câu (lớn hơn)", "Động vật"),
        (176, "puppy", "n", "/ˈpʌp.i/", "chó con", "Động vật"),
        (177, "rabbit", "n", "/ˈræb.ɪt/", "con thỏ", "Động vật"),
        (178, "raven", "n", "/ˈreɪ.vən/", "(một loại) quạ", "Động vật"),
        (179, "robin", "n", "/ˌrɑː.bɪn-/", "chim cổ đỏ", "Động vật"),
        (180, "seagull", "n", "/ˈsiː.ɡʌl/", "mòng biển, hải âu", "Động vật"),
        (181, "sheep", "n", "/ʃiːp/", "con cừu", "Động vật"),
        (182, "shrimp", "n", "/ʃrɪmp/", "con tôm", "Động vật"),
        (183, "sparrow", "n", "/ˈsper.oʊ/", "chim sẻ", "Động vật"),
        (184, "squirrel", "n", "/ˈskwɝː.əl/", "con sóc", "Động vật"),
        (185, "stork", "n", "/stɔːrk/", "con cò", "Động vật"),
        (186, "swallow", "n", "/ˈswɑː.loʊ/", "chim nhạn, én", "Động vật"),
        (187, "swan", "n", "/swɑːn/", "thiên nga", "Động vật"),
        (188, "turkey", "n", "/ˈtɝː.ki/", "con gà tây", "Động vật"),
        (189, "turtle", "n", "/ˈtɝː.t̬əl/", "con rùa", "Động vật"),
        (190, "walrus", "n", "/ˈwɑːl.rəs/", "hải mã", "Động vật"),
        (191, "woodpecker", "n", "/ˈwʊdˌpek.ɚ/", "chim gõ kiến", "Động vật"),
    
        # CHỦ ĐỀ 5: LEISURE TIME - GIẢI TRÍ (192 - 223)
        (192, "activity", "n", "/ækˈtɪv.ə.t̬i/", "hoạt động", "Giải trí"),
        (193, "art gallery", "n", "/ˈɑːrt ˌɡæl.ɚ.i/", "phòng trưng bày tranh, bảo tàng nghệ thuật", "Giải trí"),
        (194, "ballet", "n", "/bælˈeɪ/", "ba lê, kịch múa", "Giải trí"),
        (195, "bar", "n", "/bɑːr/", "quán rượu, quầy bán rượu", "Giải trí"),
        (196, "bowling", "n", "/ˈboʊ.lɪŋ/", "trò chơi lăn bóng, bowling", "Giải trí"),
        (197, "cafè", "n", "/kæfˈeɪ/", "quán cà phê", "Giải trí"),
        (198, "cheat", "n, v", "/tʃiːt/", "trò lừa đảo; gian lận, lừa đảo", "Giải trí"),
        (199, "cinema", "n", "/ˈsɪn.ə.mə/", "rạp chiếu phim", "Giải trí"),
        (200, "circus", "n", "/ˈsɝː.kəs/", "rạp xiếc", "Giải trí"),
        (201, "concert", "n", "/ˈkɑːn.sɚt/", "buổi hòa nhạc", "Giải trí"),
        (202, "concert hall", "n", "/ˈkɑːn.sɚt ˌhɑːl/", "phòng hòa nhạc", "Giải trí"),
        (203, "cosplay", "n", "/ˈkɑːz.pleɪ/", "trò chơi hóa trang", "Giải trí"),
        (204, "dartboard", "n", "/ˈdɑːrt.bɔːrd/", "tấm bia trong trò chơi phi tiêu", "Giải trí"),
        (205, "exhibition", "n", "/ˌek.səˈbɪʃ.ən/", "buổi triển lãm, trưng bày", "Giải trí"),
        (206, "exhibition center", "n", "/ˌek.səˈbɪʃ.ən ˌsen.t̬ɚ/", "hội chợ thương mại, trung tâm triển lãm", "Giải trí"),
        (207, "film", "n", "/fɪlm/", "phim, phim ảnh", "Giải trí"),
        (208, "handcraft", "n", "/ˈhænd.kræft/", "nghề thủ công, hoạt động thủ công", "Giải trí"),
        (209, "leisure centre", "n", "/ˈliː.ʒɚ ˌsen.t̬ɚ/", "khu vui chơi, trung tâm giải trí", "Giải trí"),
        (210, "monopoly", "n", "/məˈnɑː.pəl.i/", "trò chơi cờ tỷ phú", "Giải trí"),
        (211, "museum", "n", "/mjuːˈziː.əm/", "bảo tàng", "Giải trí"),
        (212, "nightclub", "n", "/ˈnaɪt.klʌb/", "hộp đêm", "Giải trí"),
        (213, "opera", "n", "/ˈɑː.pɚ.ə/", "nhạc kịch", "Giải trí"),
        (214, "opera house", "n", "/ˈɑː.pɚ.ə ˌhaʊs/", "nhà hát", "Giải trí"),
        (215, "play", "n, v", "/pleɪ/", "sự vui đùa; vui chơi", "Giải trí"),
        (216, "pub", "n", "/pʌb/", "nơi phục vụ đồ uống có cồn", "Giải trí"),
        (217, "puzzle", "n", "/ˈpʌz.əl/", "trò chơi xếp hình", "Giải trí"),
        (218, "quiz", "n", "/kwɪz/", "trò chơi đố vui", "Giải trí"),
        (219, "restaurant", "n", "/ˈres.tə.rɑːnt/", "nhà hàng ăn uống", "Giải trí"),
        (220, "soft play", "n", "/ˌsɑːft ˈpleɪ/", "trò chơi nhẹ nhàng dành cho trẻ em", "Giải trí"),
        (221, "stadium", "n", "/ˈsteɪ.di.əm/", "sân vận động", "Giải trí"),
        (222, "theater", "n", "/ˈθiː.ə.t̬ɚ/", "nhà hát, rạp hát", "Giải trí"),
        (223, "zoo", "n", "/zuː/", "sở thú", "Giải trí"),
    
        # CHỦ ĐỀ 6: HOUSE AND HOME - NHÀ CỬA (224 - 274)
        (224, "accommodation", "n", "/əˌkɑː.məˈdeɪ.ʃən/", "chỗ ở", "Nhà cửa"),
        (225, "armchair", "n", "/ˈɑːrm.tʃer/", "ghế bành, ghế có tựa tay", "Nhà cửa"),
        (226, "attic", "n", "/ˈæt̬.ɪk/", "tum, gác mái", "Nhà cửa"),
        (227, "balcony", "n", "/ˈbæl.kə.ni/", "ban công", "Nhà cửa"),
        (228, "basement", "n", "/ˈbeɪs.mənt/", "tầng hầm, nền móng", "Nhà cửa"),
        (229, "bathroom", "n", "/ˈbæθ.ruːm/", "phòng tắm", "Nhà cửa"),
        (230, "bathtub", "n", "/ˈbæθ.tʌb/", "bồn tắm", "Nhà cửa"),
        (231, "bedroom", "n", "/ˈbed.ruːm/", "phòng ngủ", "Nhà cửa"),
        (232, "bleach", "n", "/bliːtʃ/", "chất tẩy trắng", "Nhà cửa"),
        (233, "broom", "n", "/bruːm/", "cái chổi", "Nhà cửa"),
        (234, "bucket", "n", "/ˈbʌk.ɪt/", "xô", "Nhà cửa"),
        (235, "chimney", "n", "/ˈtʃɪm.ni/", "ống khói", "Nhà cửa"),
        (236, "closet", "n", "/ˈklɑː.zət/", "phòng để đồ, phòng kho", "Nhà cửa"),
        (237, "cloth", "n", "/klɑːθ/", "miếng vải, mảnh vải", "Nhà cửa"),
        (238, "cottage", "n", "/ˈkɑː.t̬ɪdʒ/", "nhà tranh", "Nhà cửa"),
        (239, "couch", "n", "/kaʊtʃ/", "ghế dài, trường kỷ, đi văng", "Nhà cửa"),
        (240, "counter", "n", "/ˈkaʊn.t̬ɚ/", "kệ bếp", "Nhà cửa"),
        (241, "doorstep", "n", "/ˈdɔːr.step/", "ngưỡng cửa, bậc cửa ra vào", "Nhà cửa"),
        (242, "doorway", "n", "/ˈdɔːr.weɪ/", "lối ra vào sát cửa", "Nhà cửa"),
        (243, "dustpan", "n", "/ˈdʌst.pæn/", "xẻng hốt rác", "Nhà cửa"),
        (244, "entrance", "n", "/ˈen.trəns/", "lối vào, cổng vào", "Nhà cửa"),
        (245, "garage", "n", "/ɡəˈrɑːʒ/", "ga ra, hầm để xe", "Nhà cửa"),
        (246, "hose", "n", "/hoʊz/", "ống cao su dài", "Nhà cửa"),
        (247, "iron", "n", "/aɪrn/", "bàn là, máy ủi", "Nhà cửa"),
        (248, "ironing board", "n", "/ˈaɪr.nɪŋ ˌbɔːrd/", "bàn để là quần áo", "Nhà cửa"),
        (249, "kettle", "n", "/ˈket̬.əl/", "ấm đun nước", "Nhà cửa"),
        (250, "kitchen", "n", "/ˈkɪtʃ.ən/", "nhà bếp", "Nhà cửa"),
        (251, "laundry basket", "n", "/ˈlɑːn.dri ˌbæs.kɪt/", "giỏ đựng quần áo", "Nhà cửa"),
        (252, "laundry detergent", "n", "/ˈlɑːn.dri dɪˌtɝː.dʒənt/", "dung dịch tẩy quần áo", "Nhà cửa"),
        (253, "mop", "n", "/mɑːp/", "chổi lau nhà", "Nhà cửa"),
        (254, "napkin", "n", "/ˈnæp.kɪn/", "khăn ăn", "Nhà cửa"),
        (255, "oven", "n", "/ˈʌv.ən/", "lò nướng", "Nhà cửa"),
        (256, "pantry", "n", "/ˈpæn.tri/", "phòng để thức ăn, phòng ăn", "Nhà cửa"),
        (257, "patio", "n", "/ˈpæt̬.i.oʊ/", "hiên, sân hè", "Nhà cửa"),
        (258, "pillow", "n", "/ˈpɪl.oʊ/", "gối", "Nhà cửa"),
        (259, "roof", "n", "/ruːf/", "mái nhà", "Nhà cửa"),
        (260, "rubber gloves", "n", "/ˈrʌb.ɚ ˌɡlʌv/", "găng tay cao su", "Nhà cửa"),
        (261, "rug", "n", "/rʌɡ/", "thảm trải sàn", "Nhà cửa"),
        (262, "scrub brush", "n", "/ˈskrʌb.ɪŋ ˌbrʌʃ/", "bàn chải cọ", "Nhà cửa"),
        (263, "shower", "n", "/ˈʃaʊ.ɚ/", "vòi hoa sen", "Nhà cửa"),
        (264, "sink", "n", "/sɪŋk/", "bồn rửa, chậu rửa mặt", "Nhà cửa"),
        (265, "sponge", "n", "/spʌndʒ/", "miếng bọt biển", "Nhà cửa"),
        (266, "squeegee mop", "n", "/ˈskwiː.dʒiː ˌmɑːp/", "chổi lau nhà dẹt", "Nhà cửa"),
        (267, "stove", "n", "/stoʊv/", "bếp lò", "Nhà cửa"),
        (268, "toaster", "n", "/ˈtoʊ.stɚ/", "máy nướng bánh mỳ", "Nhà cửa"),
        (269, "toilet", "n", "/ˈtɔɪ.lət/", "bồn cầu", "Nhà cửa"),
        (270, "towel", "n", "/taʊəl/", "khăn vải", "Nhà cửa"),
        (271, "trash can", "n", "/ˈtræʃ ˌkæn/", "thùng rác", "Nhà cửa"),
        (272, "wardrobe", "n", "/ˈwɔːr.droʊb/", "tủ quần áo", "Nhà cửa"),
        (273, "washing machine", "n", "/ˈwɑː.ʃɪŋ məˌʃiːn/", "máy giặt", "Nhà cửa"),
        (274, "window", "n", "/ˈwɪn.doʊ/", "cửa sổ", "Nhà cửa"),
    
        # CHỦ ĐỀ 7: FRUIT AND VEGETABLES - RAU QUẢ (275 - 333)
        (275, "apple", "n", "/ˈæp.əl/", "quả táo", "Rau quả"),
        (276, "apricot", "n", "/ˈeɪ.prɪ.kɑːt/", "quả mơ", "Rau quả"),
        (277, "artichoke", "n", "/ˈɑːr.t̬ə.tʃoʊk/", "Atiso", "Rau quả"),
        (278, "asparagus", "n", "/əˈsper.ə.ɡəs/", "măng tây", "Rau quả"),
        (279, "avocado", "n", "/ˌɑː.vəˈkɑː.doʊ/", "quả bơ", "Rau quả"),
        (280, "banana", "n", "/bəˈnæn.ə/", "quả chuối", "Rau quả"),
        (281, "bean", "n", "/biːn/", "hạt đậu", "Rau quả"),
        (282, "beetroot", "n", "/ˈbiːt.ruːt/", "củ cải đường, củ dền", "Rau quả"),
        (283, "blueberry", "n", "/ˈbluːˌbər.i/", "việt quất", "Rau quả"),
        (284, "broccoli", "n", "/ˈbrɑː.kəl.i/", "bông cải xanh", "Rau quả"),
        (285, "Brussels sprout", "n", "/ˌbrʌs.əlz ˈspraʊt/", "cải Brussel", "Rau quả"),
        (286, "cabbage", "n", "/ˈkæb.ɪdʒ/", "bắp cải", "Rau quả"),
        (287, "carrot", "n", "/ˈker.ət/", "củ cà rốt", "Rau quả"),
        (288, "cauliflower", "n", "/ˈkɑː.ləˌflaʊ.ɚ/", "súp lơ", "Rau quả"),
        (289, "celery", "n", "/ˈsel.ɚ.i/", "cần tây", "Rau quả"),
        (290, "cherry", "n", "/ˈtʃer.i/", "quả anh đào", "Rau quả"),
        (291, "chili pepper", "n", "/ˈtʃɪl·i (ˌpep·ər)/", "ớt đỏ", "Rau quả"),
        (292, "coconut", "n", "/ˈkoʊ.kə.nʌt/", "quả dừa", "Rau quả"),
        (293, "corn", "n", "/kɔːrn/", "ngô, bắp", "Rau quả"),
        (294, "courgette/ Zucchini", "n", "/kʊrˈʒet/ /zuːˈkiː.ni/", "bí ngòi", "Rau quả"),
        (295, "cucumber", "n", "/ˈkjuː.kʌm.bɚ/", "dưa chuột", "Rau quả"),
        (296, "eggplant", "n", "/ˈeɡ.plænt/", "cà tím, cà bung", "Rau quả"),
        (297, "garlic", "n", "/ˈɡɑːr.lɪk/", "tỏi", "Rau quả"),
        (298, "ginger", "n", "/ˈdʒɪn.dʒɚ/", "gừng", "Rau quả"),
        (299, "grape", "n", "/ɡreɪp/", "nho", "Rau quả"),
        (300, "grapefruit", "n", "/ˈɡreɪp.fruːt/", "bưởi chùm (lai giữa cam và bưởi)", "Rau quả"),
        (301, "jackfruit", "n", "/ˈdʒæk.fruːt/", "quả mít", "Rau quả"),
        (302, "kiwi", "n", "/ˈkiː.wiː/", "quả kiwi (dương đào)", "Rau quả"),
        (303, "leek", "n", "/liːk/", "tỏi tây", "Rau quả"),
        (304, "lemon", "n", "/ˈlem.ən/", "chanh vàng", "Rau quả"),
        (305, "lettuce", "n", "/ˈlet̬.ɪs/", "ra diếp", "Rau quả"),
        (306, "lime", "n", "/laɪm/", "chanh xanh", "Rau quả"),
        (307, "mandarin", "n", "/ˈmæn.dɚ.ɪn/", "quả quýt", "Rau quả"),
        (308, "mango", "n", "/ˈmæŋ.ɡoʊ/", "quả xoài", "Rau quả"),
        (309, "melon", "n", "/ˈmel.ən/", "quả dưa", "Rau quả"),
        (310, "mushroom", "n", "/ˈmʌʃ.ruːm/", "nấm", "Rau quả"),
        (311, "nectarine", "n", "/ˌnek.təˈriːn/", "quả xuân đào", "Rau quả"),
        (312, "onion", "n", "/ˈʌn.jən/", "củ hành", "Rau quả"),
        (313, "orange", "n", "/ˈɔːr.ɪndʒ/", "quả cam", "Rau quả"),
        (314, "papaya", "n", "/pəˈpaɪ.ə/", "quả đu đủ", "Rau quả"),
        (315, "pea", "n", "/piː/", "đậu Hà Lan", "Rau quả"),
        (316, "peach", "n", "/piːtʃ/", "quả đào", "Rau quả"),
        (317, "pear", "n", "/per/", "quả lê", "Rau quả"),
        (318, "pineapple", "n", "/ˈpaɪnˌæp.əl/", "quả dứa", "Rau quả"),
        (319, "plum", "n", "/plʌm/", "quả mận", "Rau quả"),
        (320, "pomegranate", "n", "/ˈpɑː.məˌɡræn.ɪt/", "quả lưu", "Rau quả"),
        (321, "potato", "n", "/pəˈteɪ.t̬oʊ/", "củ khoai tây", "Rau quả"),
        (322, "pumpkin", "n", "/ˈpʌmp.kɪn/", "bí ngô, bí đỏ", "Rau quả"),
        (323, "radish", "n", "/ˈræd.ɪʃ/", "củ cải đỏ", "Rau quả"),
        (324, "raspberry", "n", "/ˈræz.ber.i/", "quả mâm xôi", "Rau quả"),
        (325, "spinach", "n", "/ˈspɪn.ɪtʃ/", "rau bina", "Rau quả"),
        (326, "spring Onion", "n", "/ˌsprɪŋ ˈʌn.jən/", "hành lá xanh", "Rau quả"),
        (327, "squash", "n", "/skwɑːʃ/", "cây bí, quả bí", "Rau quả"),
        (328, "starfruit", "n", "/ˈstɑːr.fruːt/", "quả khế", "Rau quả"),
        (329, "strawberry", "n", "/ˈstrɑːˌber.i/", "quả dâu tây", "Rau quả"),
        (330, "sweet potato", "n", "/ˌswiːt pəˈteɪ.t̬oʊ/", "khoai lang", "Rau quả"),
        (331, "tomato", "n", "/təˈmeɪ.t̬oʊ/", "quả cà chua", "Rau quả"),
        (332, "turnip", "n", "/ˈtɝː.nɪp/", "củ cải trắng", "Rau quả"),
        (333, "watermelon", "n", "/ˈwɑː.t̬ɚˌmel.ən/", "dưa hấu", "Rau quả"),
    
        # CHỦ ĐỀ 8: CHARACTERISTICS - TÍNH CÁCH (334 - 423)
        (334, "active", "adj", "/ˈæk.tɪv/", "năng nổ, lanh lợi", "Tính cách"),
        (335, "alert", "adj", "/əˈlɝːt/", "tỉnh táo, cảnh giác", "Tính cách"),
        (336, "ambitious", "adj", "/æmˈbɪʃ.əs/", "tham vọng", "Tính cách"),
        (337, "attentive", "adj", "/əˈten.t̬ɪv/", "chăm chú, chú tâm", "Tính cách"),
        (338, "bold", "adj", "/boʊld/", "táo bạo, mạo hiểm", "Tính cách"),
        (339, "brave", "adj", "/breɪv/", "dũng cảm, gan dạ", "Tính cách"),
        (340, "careful", "adj", "/ˈker.fəl/", "cẩn thận, thận trọng", "Tính cách"),
        (341, "careless", "adj", "/ˈker.ləs/", "bất cẩn, cẩu thả", "Tính cách"),
        (342, "cautious", "adj", "/ˈkɑː.ʃəs/", "thận trọng, cẩn thận", "Tính cách"),
        (343, "conscientious", "adj", "/ˌkɑːn.ʃiˈen.ʃəs/", "chu đáo, tỉ mỉ", "Tính cách"),
        (344, "courageous", "adj", "/kəˈreɪ.dʒəs/", "can đảm", "Tính cách"),
        (345, "crafty", "adj", "/ˈkræf.ti/", "láu cá, xảo quyệt", "Tính cách"),
        (346, "cunning", "adj", "/ˈkʌn.ɪŋ/", "xảo trá, khôn lỏi", "Tính cách"),
        (347, "deceitful", "adj", "/dɪˈsiːt.fəl/", "dối trá", "Tính cách"),
        (348, "decent", "adj", "/ˈdiː.sənt/", "lịch sự, tao nhã", "Tính cách"),
        (349, "dependable", "adj", "/dɪˈpen.də.bəl/", "đáng tin cậy", "Tính cách"),
        (350, "determined", "adj", "/dɪˈtɝː.mɪnd/", "quyết tâm", "Tính cách"),
        (351, "devoted", "adj", "/dɪˈvoʊ.t̬ɪd/", "hết lòng, tận tâm, tận tụy", "Tính cách"),
        (352, "diligent", "adj", "/ˈdɪl.ə.dʒənt/", "siêng năng, cần cù", "Tính cách"),
        (353, "disciplined", "adj", "/ˈdɪs.ə.plɪnd/", "có tính kỷ luật", "Tính cách"),
        (354, "dishonest", "adj", "/dɪˈsɑː.nɪst/", "bất lương, dối trá", "Tính cách"),
        (355, "disloyal", "adj", "/ˌdɪsˈlɔɪ.əl/", "phản trắc, phản bội", "Tính cách"),
        (356, "energetic", "adj", "/ˌen.ɚˈdʒet̬.ɪk/", "giàu năng lượng", "Tính cách"),
        (357, "fair", "adj", "/fer/", "ngay thẳng", "Tính cách"),
        (358, "faithful", "adj", "/ˈfeɪθ.fəl/", "trung thành, chung thủy", "Tính cách"),
        (359, "fearless", "adj", "/ˈfɪr.ləs/", "bạo dạn", "Tính cách"),
        (360, "forgetful", "adj", "/fɚˈɡet.fəl/", "hay quên", "Tính cách"),
        (361, "hard-headed", "adj", "/ˌhɑːrdˈhed.ɪd/", "cứng đầu, ương ngạnh", "Tính cách"),
        (362, "hardworking", "adj", "/ˈhɑrdˈwɜr·kɪŋ/", "chăm chỉ, chịu khó", "Tính cách"),
        (363, "hardy", "adj", "/ˈhɑːr.di/", "táo bạo, gan dạ", "Tính cách"),
        (364, "honest", "adj", "/ˈɑː.nɪst/", "chân thật, trung thành", "Tính cách"),
        (365, "idle", "adj", "/ˈaɪ.dəl/", "nhàn rỗi, lười nhác", "Tính cách"),
        (366, "immature", "adj", "/ˌɪm.əˈtʊr/", "non nớt, thiếu chín chắn", "Tính cách"),
        (367, "impartial", "adj", "/ɪmˈpɑːr.ʃəl/", "trung lập, ngay thẳng", "Tính cách"),
        (368, "inattentive", "adj", "/ˌɪn.əˈten.t̬ɪv/", "lơ đễnh, thiếu tập trung", "Tính cách"),
        (369, "independent", "adj", "/ˌɪn.dɪˈpen.dənt/", "tự lập", "Tính cách"),
        (370, "inert", "adj", "/ˌɪnˈɝːt/", "trì trệ, chậm chạp", "Tính cách"),
        (371, "insightful", "adj", "/ˈɪn.saɪt.fəl/", "sâu sắc, sáng suốt", "Tính cách"),
        (372, "insincere", "adj", "/ˌɪn.sɪnˈsɪr/", "không thành thực, giả dối", "Tính cách"),
        (373, "irrational", "adj", "/ɪˈræʃ.ən.əl/", "không hợp lý", "Tính cách"),
        (374, "irresponsible", "adj", "/ˌɪr.əˈspɑːn.sə.bəl/", "thiếu trách nhiệm", "Tính cách"),
        (375, "lazy", "adj", "/ˈleɪ.zi/", "lười biếng", "Tính cách"),
        (376, "level-headed", "adj", "/ˌlev.əlˈhed.ɪd/", "bình tĩnh, điềm đạm", "Tính cách"),
        (377, "loyal", "adj", "/ˈlɔɪ.əl/", "trung thành, trung kiên", "Tính cách"),
        (378, "mature", "adj", "/məˈtʊr/", "trưởng thành, chững chạc", "Tính cách"),
        (379, "methodical", "adj", "/məˈθɑː.dɪ.kəl/", "ngăn nắp, cẩn thận", "Tính cách"),
        (380, "naive", "adj", "/naɪˈiːv/", "ngây thơ", "Tính cách"),
        (381, "objective", "adj", "/əbˈdʒek.tɪv/", "khách quan", "Tính cách"),
        (382, "observant", "adj", "/əbˈzɝː.vənt/", "tinh ý, hay quan sát", "Tính cách"),
        (383, "opinionated", "adj", "/əˈpɪn.jə.neɪ.t̬ɪd/", "cứng đầu, ngoan cố", "Tính cách"),
        (384, "organized", "adj", "/ˈɔːr.ɡən.aɪzd/", "có trật tự, ngăn nắp", "Tính cách"),
        (385, "passive", "adj", "/ˈpæs.ɪv/", "nhiệt huyết", "Tính cách"),
        (386, "perceptive", "adj", "/pɚˈsep.tɪv/", "mẫn cảm, sâu sắc", "Tính cách"),
        (387, "persevering", "adj", "/ˌpɝː.səˈvɪr.ɪŋ/", "kiên nhẫn, bền bỉ", "Tính cách"),
        (388, "practical", "adj", "/ˈpræk.tɪ.kəl/", "thực tế, thực tiễn", "Tính cách"),
        (389, "prudent", "adj", "/ˈpruː.dənt/", "thận trọng, khôn ngoan", "Tính cách"),
        (390, "quick", "adj", "/kwɪk/", "nhanh nhẹn", "Tính cách"),
        (391, "rational", "adj", "/ˈræʃ.ən.əl/", "có lý trí", "Tính cách"),
        (392, "reasonable", "adj", "/ˈriː.zən.ə.bəl/", "biết điều", "Tính cách"),
        (393, "reckless", "adj", "/ˈrek.ləs/", "liều lĩnh, táo bạo", "Tính cách"),
        (394, "reliable", "adj", "/rɪˈlaɪ.ə.bəl/", "đáng tin tưởng", "Tính cách"),
        (395, "resolute", "adj", "/ˈrez.ə.luːt/", "cương quyết", "Tính cách"),
        (396, "responsible", "adj", "/rɪˈspɑːn.sə.bəl/", "có trách nhiệm", "Tính cách"),
        (397, "scrupulous", "adj", "/ˈskruː.pjə.ləs/", "kĩ lưỡng, tỉ mỉ, thận trọng", "Tính cách"),
        (398, "sensible", "adj", "/ˈsen.sə.bəl/", "khôn ngoan, có óc phán xét", "Tính cách"),
        (399, "shallow", "adj", "/ˈʃæl.oʊ/", "nông cạn", "Tính cách"),
        (400, "shrewd", "adj", "/ʃruːd/", "khôn ngoan", "Tính cách"),
        (401, "sincere", "adj", "/sɪnˈsɪr/", "chân thành", "Tính cách"),
        (402, "slow", "adj", "/sloʊ/", "chậm chạp", "Tính cách"),
        (403, "sluggish", "adj", "/ˈslʌɡ.ɪʃ/", "uể oải, lờ đờ", "Tính cách"),
        (404, "sly", "adj", "/slaɪ/", "ranh mãnh, quỷ quyệt", "Tính cách"),
        (405, "strong", "adj", "/strɑːŋ/", "mạnh mẽ, đanh thép", "Tính cách"),
        (406, "strong-minded", "adj", "/ˌstrɑːŋˈmaɪn.dɪd/", "cứng cỏi, kiên quyết", "Tính cách"),
        (407, "strong-willed", "adj", "/ˌstrɑːŋˈwɪld/", "cứng cỏi", "Tính cách"),
        (408, "stubborn", "adj", "/ˈstʌb.ɚn/", "bướng bỉnh, ngang ngạnh", "Tính cách"),
        (409, "superficial", "adj", "/ˌsuː.pɚˈfɪʃ.əl/", "hời hợt, nông cạn", "Tính cách"),
        (410, "superstitious", "adj", "/ˌsuː.pɚˈstɪʃ.əs/", "mê tín", "Tính cách"),
        (411, "thorough", "adj", "/ˈθɝː.ə/", "kỹ lưỡng, thấu đáo", "Tính cách"),
        (412, "timid", "adj", "/ˈtɪm.ɪd/", "rụt rè, bẽn lẽn", "Tính cách"),
        (413, "tough", "adj", "/tʌf/", "cứng rắn", "Tính cách"),
        (414, "treacherous", "adj", "/ˈtretʃ.ɚ.əs/", "bội bạc", "Tính cách"),
        (415, "trustworthy", "adj", "/ˈtrʌstˌwɝː.ði/", "đáng tin", "Tính cách"),
        (416, "truthful", "adj", "/ˈtruːθ.fəl/", "thật thà, chân thật", "Tính cách"),
        (417, "unbiased", "adj", "/ʌnˈbaɪəst/", "không thiên vị", "Tính cách"),
        (418, "unpredictable", "adj", "/ˌʌn.prɪˈdɪk.tə.bəl/", "khó đoán, khôn lường", "Tính cách"),
        (419, "unreasonable", "adj", "/ʌnˈriː.zən.ə.bəl/", "vô lý, quá đáng", "Tính cách"),
        (420, "unreliable", "adj", "/ˌʌn.rɪˈlaɪə.bəl/", "không đáng tin", "Tính cách"),
        (421, "unscrupulous", "adj", "/ʌnˈskruː.pjə.ləs/", "cẩu thả", "Tính cách"),
        (422, "vigorous", "adj", "/ˈvɪɡ.ɚ.əs/", "mạnh mẽ, sôi nổi", "Tính cách"),
        (423, "weak", "adj", "/wiːk/", "yếu đuối", "Tính cách"),
    
        # CHỦ ĐỀ 9: BODY PARTS - BỘ PHẬN CƠ THỂ (424 - 452)
        (424, "ankle", "n", "/ˈæŋ.kəl/", "mắt cá chân", "Bộ phận cơ thể"),
        (425, "arm", "n", "/ɑːrm/", "cánh tay", "Bộ phận cơ thể"),
        (426, "armpit", "n", "/ˈɑːrm.pɪt/", "nách", "Bộ phận cơ thể"),
        (427, "beard", "n", "/bɪrd/", "râu", "Bộ phận cơ thể"),
        (428, "breast", "n", "/brest/", "ngực, vú (phụ nữ)", "Bộ phận cơ thể"),
        (429, "calf", "n", "/kæf/", "bắp chân", "Bộ phận cơ thể"),
        (430, "cheek", "n", "/tʃiːk/", "má", "Bộ phận cơ thể"),
        (431, "chest", "n", "/tʃest/", "ngực (chung)", "Bộ phận cơ thể"),
        (432, "chin", "n", "/tʃɪn/", "cằm", "Bộ phận cơ thể"),
        (433, "earlobe", "n", "/ˈɪr.loʊb/", "dái tai", "Bộ phận cơ thể"),
        (434, "elbow", "n", "/ˈel.boʊ/", "khuỷu tay", "Bộ phận cơ thể"),
        (435, "eyebrow", "n", "/ˈaɪ.braʊ/", "lông mày", "Bộ phận cơ thể"),
        (436, "eyelash", "n", "/ˈaɪ.læʃ/", "lông mi", "Bộ phận cơ thể"),
        (437, "eyelid", "n", "/ˈaɪ.lɪd/", "mí mắt", "Bộ phận cơ thể"),
        (438, "face", "n", "/feɪs/", "gương mặt", "Bộ phận cơ thể"),
        (439, "finger", "n", "/ˈfɪŋ.ɡɚ/", "ngón tay", "Bộ phận cơ thể"),
        (440, "forearm", "n", "/ˈfɔːr.ɑːrm/", "cẳng tay", "Bộ phận cơ thể"),
        (441, "forehead", "n", "/ˈfɑː.rɪd/", "trán", "Bộ phận cơ thể"),
        (442, "gum", "n", "/ɡʌm/", "nướu, lợi", "Bộ phận cơ thể"),
        (443, "heel", "n", "/hiːl/", "gót chân", "Bộ phận cơ thể"),
        (444, "hip", "n", "/hɪp/", "hông", "Bộ phận cơ thể"),
        (445, "index finger", "n", "/ˈɪn.deks ˌfɪŋ.ɡɚ/", "ngón tay trỏ", "Bộ phận cơ thể"),
        (446, "jaw", "n", "/dʒɑː/", "hàm, quai hàm", "Bộ phận cơ thể"),
        (447, "knee", "n", "/niː/", "đầu gối", "Bộ phận cơ thể"),
        (448, "knuckle", "n", "/ˈnʌk.əl/", "khớp đốt ngón tay", "Bộ phận cơ thể"),
        (449, "leg", "n", "/leɡ/", "chân", "Bộ phận cơ thể"),
        (450, "lip", "n", "/lɪp/", "môi", "Bộ phận cơ thể"),
        (451, "mouth", "n", "/maʊθ/", "miệng", "Bộ phận cơ thể"),
        (452, "mustache", "n", "/ˈmʌs.tæʃ/", "râu mép, ria", "Bộ phận cơ thể"),
    
        # CHỦ ĐỀ 10: FOOD AND DRINKS - ĐỒ ĂN VÀ THỨC UỐNG (453 - 487)
        (453, "bacon", "n", "/ˈbeɪ.kən/", "thịt xông khói", "Đồ ăn thức uống"),
        (454, "bagel", "n", "/ˈbeɪ.ɡəl/", "bánh vòng", "Đồ ăn thức uống"),
        (455, "baguette", "n", "/bæɡˈet/", "bánh mỳ dài", "Đồ ăn thức uống"),
        (456, "breadstick", "n", "/ˈbred.stɪk/", "bánh mỳ que", "Đồ ăn thức uống"),
        (457, "cheese", "n", "/tʃiːz/", "phó mát", "Đồ ăn thức uống"),
        (458, "chicken nugget", "n", "/ˈtʃɪk.ɪn ˈnʌɡ.ɪt/", "gà viên chiên", "Đồ ăn thức uống"),
        (459, "coffee", "n", "/ˈkɑː.fi/", "cà phê", "Đồ ăn thức uống"),
        (460, "croissant", "n", "/kwɑːˈsɑ̃ː/", "bánh sừng bò", "Đồ ăn thức uống"),
        (461, "donut", "n", "/ˈdoʊ.nʌt/", "bánh rán", "Đồ ăn thức uống"),
        (462, "egg", "n", "/eɡ/", "trứng", "Đồ ăn thức uống"),
        (463, "fish and chips", "n", "/ˌfɪʃ en ˈtʃɪps/", "cá tẩm bột chiên dùng với khoai tây chiên", "Đồ ăn thức uống"),
        (464, "French fries", "n", "/ˈfrentʃ ˈfrɑɪz/", "khoai tây chiên", "Đồ ăn thức uống"),
        (465, "ham", "n", "/hæm/", "thịt giăm bông muối", "Đồ ăn thức uống"),
        (466, "hamburger", "n", "/ˈhæmˌbɝː.ɡɚ/", "lát thịt băm hình tròn (thường kẹp với bánh mỳ)", "Đồ ăn thức uống"),
        (467, "hot chocolate", "n", "/ˌhɑːt ˈtʃɑːk.lət/", "sô cô la nóng", "Đồ ăn thức uống"),
        (468, "hot dog", "n", "/ˈhɑːt ˌdɑːɡ/", "bánh mỳ kẹp xúc xích", "Đồ ăn thức uống"),
        (469, "ice cream", "n", "/ˈaɪs ˌkriːm/", "kem", "Đồ ăn thức uống"),
        (470, "jelly roll", "n", "/ˈdʒel.i ˌroʊl/", "bánh cuộn (mứt, sô cô la...)", "Đồ ăn thức uống"),
        (471, "marmalade", "n", "/ˈmɑːr.mə.leɪd/", "mứt cam", "Đồ ăn thức uống"),
        (472, "milk", "n", "/mɪlk/", "sữa", "Đồ ăn thức uống"),
        (473, "muffin", "n", "/ˈmʌf.ɪn/", "bánh nướng xốp", "Đồ ăn thức uống"),
        (474, "onion ring", "n", "/ˈʌn.jən ˌrɪŋ/", "vòng hành", "Đồ ăn thức uống"),
        (475, "orange juice", "n", "/ˈɔːr.ɪndʒ ˌdʒuːs/", "nước cam", "Đồ ăn thức uống"),
        (476, "pancake", "n", "/ˈpæn.keɪk/", "bánh kếp", "Đồ ăn thức uống"),
        (477, "pita", "n", "/ˈpɪt̬.ə/", "bánh mỳ ổ tròn dẹt", "Đồ ăn thức uống"),
        (478, "pizza", "n", "/ˈpiːt.sə/", "bánh pizza", "Đồ ăn thức uống"),
        (479, "porridge", "n", "/ˈpɔːr.ɪdʒ/", "cháo đặc", "Đồ ăn thức uống"),
        (480, "pretzel", "n", "/ˈpret.səl/", "bánh xoắn", "Đồ ăn thức uống"),
        (481, "salad", "n", "/ˈsæl.əd/", "rau trộn, nộm rau", "Đồ ăn thức uống"),
        (482, "sandwich", "n", "/ˈsæn.wɪtʃ/", "bánh mỳ kẹp", "Đồ ăn thức uống"),
        (483, "sausage", "n", "/ˈsɑː.sɪdʒ/", "xúc xích", "Đồ ăn thức uống"),
        (484, "taco", "n", "/ˈtɑː.koʊ/", "bánh kẹp Mexico", "Đồ ăn thức uống"),
        (485, "toast", "n", "/toʊst/", "bánh mỳ nướng", "Đồ ăn thức uống"),
        (486, "waffle", "n", "/ˈwɑː.fəl/", "bánh quế", "Đồ ăn thức uống"),
        (487, "yogurt", "n", "/ˈjoʊ.ɡɚt/", "sữa chua", "Đồ ăn thức uống"),
    
        # CHỦ ĐỀ 11: BODY MOVEMENTS - ĐỘNG TÁC (488 - 532)
        (488, "bend", "v", "/bend/", "cúi, uốn cong", "Động tác"),
        (489, "break", "v", "/breɪk/", "làm vỡ, bẻ gãy", "Động tác"),
        (490, "carry", "v", "/ˈker.i/", "mang, vác", "Động tác"),
        (491, "cartwheel", "v", "/ˈkɑːrt.wiːl/", "nhào lộn", "Động tác"),
        (492, "catch", "v", "/kætʃ/", "bắt, đỡ", "Động tác"),
        (493, "clap", "v", "/klæp/", "vỗ tay", "Động tác"),
        (494, "crawl", "v", "/krɑːl/", "bò, trườn", "Động tác"),
        (495, "cry", "v", "/kraɪ/", "khóc lóc", "Động tác"),
        (496, "dance", "v", "/dæns/", "nhảy múa, khiêu vũ", "Động tác"),
        (497, "dive", "v", "/daɪv/", "nhảy lao xuống nước, lặn", "Động tác"),
        (498, "drag", "v", "/dræɡ/", "lôi, kéo", "Động tác"),
        (499, "drop", "v", "/drɑːp/", "làm rơi", "Động tác"),
        (500, "hit", "v", "/hɪt/", "đánh, va phải", "Động tác"),
        (501, "hold", "v", "/hoʊld/", "nắm, giữ", "Động tác"),
        (502, "jog", "v", "/dʒɑːɡ/", "chạy bộ", "Động tác"),
        (503, "jump", "v", "/dʒʌmp/", "nhảy, giật mình", "Động tác"),
        (504, "kick", "v", "/kɪk/", "đá", "Động tác"),
        (505, "kiss", "v", "/kɪs/", "hôn", "Động tác"),
        (506, "kneel", "v", "/niːl/", "quỳ gối", "Động tác"),
        (507, "laugh", "v", "/læf/", "cười lớn", "Động tác"),
        (508, "lean", "v", "/liːn/", "dựa, tựa", "Động tác"),
        (509, "leap", "v", "/liːp/", "nhảy vọt", "Động tác"),
        (510, "lie down", "v", "/laɪ daʊn/", "nằm xuống, ngả lưng", "Động tác"),
        (511, "lift", "v", "/lɪft/", "nâng lên", "Động tác"),
        (512, "look", "v", "/lʊk/", "nhìn, ngắm", "Động tác"),
        (513, "march", "v", "/mɑːrtʃ/", "diễu hành, hành quân", "Động tác"),
        (514, "open", "v", "/ˈoʊ.pən/", "mở ra", "Động tác"),
        (515, "point", "v", "/pɔɪnt/", "chỉ, trỏ", "Động tác"),
        (516, "pour", "v", "/pɔːr/", "đổ, rót", "Động tác"),
        (517, "pull", "v", "/pʊl/", "kéo", "Động tác"),
        (518, "punch", "v", "/pʌntʃ/", "đấm, thọi", "Động tác"),
        (519, "push", "v", "/pʊʃ/", "xô đẩy", "Động tác"),
        (520, "put down", "v", "/pʊt daʊn/", "đặt xuống", "Động tác"),
        (521, "run", "v", "/rʌn/", "chạy", "Động tác"),
        (522, "sit", "v", "/sɪt/", "ngồi", "Động tác"),
        (523, "slip", "v", "/slɪp/", "trượt, tuột", "Động tác"),
        (524, "squat", "v", "/skwɑːt/", "ngồi xổm", "Động tác"),
        (525, "stand", "v", "/stænd/", "đứng yên", "Động tác"),
        (526, "stretch", "v", "/stretʃ/", "vươn (vai..), ưỡn lưng", "Động tác"),
        (527, "talk", "v", "/tɑːk/", "nói chuyện, trò chuyện", "Động tác"),
        (528, "throw", "v", "/θroʊ/", "ném, quăng, vứt", "Động tác"),
        (529, "tiptoe", "v", "/ˈtɪp.toʊ/", "đi nhón chân", "Động tác"),
        (530, "trip", "v", "/trɪp/", "ngáng chân, vấp ngã", "Động tác"),
        (531, "walk", "v", "/wɑːk/", "đi bộ", "Động tác"),
        (532, "wave", "v", "/weɪv/", "vẫy tay", "Động tác"),
    
        # CHỦ ĐỀ 12: CLOTHES AND ACCESSORIES - QUẦN ÁO VÀ PHỤ KIỆN (533 - 568)
        (533, "bathrobe", "n", "/ˈbæθ.roʊb/", "áo choàng tắm", "Quần áo & Phụ kiện"),
        (534, "belt", "n", "/belt/", "thắt lưng", "Quần áo & Phụ kiện"),
        (535, "blazer", "n", "/ˈbleɪ.zɚ/", "áo khoác dáng dài", "Quần áo & Phụ kiện"),
        (536, "boot", "n", "/buːt/", "ủng, giày cao cổ", "Quần áo & Phụ kiện"),
        (537, "bow tie", "n", "/ˌboʊ ˈtaɪ/", "nơ con bướm", "Quần áo & Phụ kiện"),
        (538, "cap", "n", "/kæp/", "mũ lưỡi trai", "Quần áo & Phụ kiện"),
        (539, "cardigan", "n", "/ˈkɑːr.dɪ.ɡən/", "áo đan len", "Quần áo & Phụ kiện"),
        (540, "cargo pants", "n", "/ˈkɑːr.ɡoʊ ˌpænts/", "quần túi hộp", "Quần áo & Phụ kiện"),
        (541, "flip-flop", "n", "/ˈflɪp.flɑːp/", "dép tông, dép xỏ ngón", "Quần áo & Phụ kiện"),
        (542, "glasses", "n", "/ˈɡlæs·əz/", "kính mắt", "Quần áo & Phụ kiện"),
        (543, "gloves", "n", "/ɡlʌv/", "găng tay, bao tay", "Quần áo & Phụ kiện"),
        (544, "handbag", "n", "/ˈhænd.bæɡ/", "túi xách", "Quần áo & Phụ kiện"),
        (545, "Hawaiian shirt", "n", "/həˌwaɪ.ən ˈʃɝːt/", "áo sơ mi Hawaii", "Quần áo & Phụ kiện"),
        (546, "jacket", "n", "/ˈdʒæk.ɪt/", "áo vét", "Quần áo & Phụ kiện"),
        (547, "jeans", "n", "/dʒiːnz/", "quần bò jeans", "Quần áo & Phụ kiện"),
        (548, "jumper", "n", "/ˈdʒʌm.pɚ/", "áo len chui đầu", "Quần áo & Phụ kiện"),
        (549, "polo shirt", "n", "/ˈpoʊ.loʊ ˌʃɝːt/", "áo polo có cổ", "Quần áo & Phụ kiện"),
        (550, "pullover", "n", "/ˈpʊlˌoʊ.vɚ/", "áo len chui đầu", "Quần áo & Phụ kiện"),
        (551, "scarf", "n", "/skɑːrf/", "khăn choàng", "Quần áo & Phụ kiện"),
        (552, "shirt", "n", "/ʃɝːt/", "áo sơ mi", "Quần áo & Phụ kiện"),
        (553, "shorts", "n", "/ʃɔːrts/", "quần sóoc, quần đùi", "Quần áo & Phụ kiện"),
        (554, "singlet", "n", "/ˈsɪŋ.ɡlət/", "áo lót, áo may ô", "Quần áo & Phụ kiện"),
        (555, "socks", "n", "/sɑːk/", "tất, vớ", "Quần áo & Phụ kiện"),
        (556, "suit", "n", "/suːt/", "bộ com lê, Âu phục", "Quần áo & Phụ kiện"),
        (557, "sunglasses", "n", "/ˈsʌnˌɡlæs.ɪz/", "kính râm, kính mát", "Quần áo & Phụ kiện"),
        (558, "sweater", "n", "/ˈswet̬.ɚ/", "áo len dài tay", "Quần áo & Phụ kiện"),
        (559, "swimsuit", "n", "/ˈswɪm.suːt/", "đồ tắm, đồ bơi", "Quần áo & Phụ kiện"),
        (560, "t-shirt", "n", "/ˈtiː.ʃɝːt/", "áo phông", "Quần áo & Phụ kiện"),
        (561, "tie", "n", "/taɪ/", "cà vạt, nơ", "Quần áo & Phụ kiện"),
        (562, "trench coat", "n", "/ˈtrentʃ ˌkoʊt/", "áo choàng", "Quần áo & Phụ kiện"),
        (563, "umbrella", "n", "/ʌmˈbrel.ə/", "ô", "Quần áo & Phụ kiện"),
        (564, "underpants", "n", "/ˈʌn.dɚ.pænts/", "đồ lót nam", "Quần áo & Phụ kiện"),
        (565, "vest", "n", "/vest/", "áo gi-lê, áo vét", "Quần áo & Phụ kiện"),
        (566, "waistcoat", "n", "/ˈwes.kət/", "áo gi-lê (áo chẽn)", "Quần áo & Phụ kiện"),
        (567, "wallet", "n", "/ˈwɑː.lɪt/", "ví, bóp", "Quần áo & Phụ kiện"),
        (568, "watch", "n", "/wɑːtʃ/", "đồng hồ", "Quần áo & Phụ kiện"),
    
        # CHỦ ĐỀ 13: EMOTIONS AND FEELINGS - CẢM XÚC (569 - 698)
        (569, "accepting", "adj", "/əkˈsep.tɪŋ/", "chấp nhận", "Cảm xúc"),
        (570, "admiration", "n", "/ˌæd.məˈreɪ.ʃən/", "sự ngưỡng mộ", "Cảm xúc"),
        (571, "adoring", "adj", "/əˈdɔːr.ɪŋ/", "tha thiết, trìu mến", "Cảm xúc"),
        (572, "annoyed", "adj", "/əˈnɔɪd/", "khó chịu, bực bội, bị làm phiền", "Cảm xúc"),
        (573, "antsy", "adj", "/ˈænt.si/", "căng thẳng, sốt ruột", "Cảm xúc"),
        (574, "anxious", "adj", "/ˈæŋk.ʃəs/", "lo âu, bồn chồn", "Cảm xúc"),
        (575, "apologetic", "adj", "/əˌpɑː.ləˈdʒet̬.ɪk/", "hối lỗi, biện hộ", "Cảm xúc"),
        (576, "appalled", "adj", "/əˈpɑːld/", "kinh hãi, sợ sệt", "Cảm xúc"),
        (577, "astonished", "adj", "/əˈstɑː.nɪʃt/", "kinh ngạc", "Cảm xúc"),
        (578, "awed", "adj", "/ɑːd/", "thán phục, nể sợ", "Cảm xúc"),
        (579, "bashful", "adj", "/ˈbæʃ.fəl/", "rụt rè, bẽn lẽn", "Cảm xúc"),
        (580, "bemused", "adj", "/bɪˈmjuːzd/", "sửng sốt, kinh ngạc", "Cảm xúc"),
        (581, "bored", "adj", "/bɔːrd/", "buồn chán, tẻ nhạt", "Cảm xúc"),
        (582, "bothered", "adj", "/ˈbɑː.ðɚd/", "bực mình, khó chịu", "Cảm xúc"),
        (583, "brooding", "adj", "/ˈbruː.dɪŋ/", "ủ ê, não nề", "Cảm xúc"),
        (584, "calm", "adj", "/kɑːm/", "bình tĩnh", "Cảm xúc"),
        (585, "captivated", "adj", "|ˈkæptɪveɪtɪd|", "bị hớp hồn, choáng ngợp", "Cảm xúc"),
        (586, "carefree", "adj", "/ˈker.friː/", "vô tư lự", "Cảm xúc"),
        (587, "certain", "adj", "/ˈsɝː.tən/", "quả quyết, chắc chắn", "Cảm xúc"),
        (588, "clueless", "adj", "/ˈkluː.ləs/", "ngây người", "Cảm xúc"),
        (589, "cold", "adj", "/koʊld/", "lạnh lùng", "Cảm xúc"),
        (590, "cranky", "adj", "/ˈkræŋ.ki/", "kỳ quặc", "Cảm xúc"),
        (591, "delighted", "adj", "/dɪˈlaɪ.t̬ɪd/", "vui mừng, mừng rỡ", "Cảm xúc"),
        (592, "delirious", "adj", "/dɪˈlɪr.i.əs/", "cuồng nhiệt, điên cuồng", "Cảm xúc"),
        (593, "derisive", "adj", "/dɪˈraɪ.sɪv/", "nhạo báng, giễu cợt", "Cảm xúc"),
        (594, "desperate", "adj", "/ˈdes.pɚ.ət/", "tuyệt vọng, chán trường", "Cảm xúc"),
        (595, "disturbed", "adj", "/dɪˈstɝːbd/", "bối rối, lúng túng", "Cảm xúc"),
        (596, "dopey", "adj", "/ˈdoʊ.pi/", "mơ màng, uể oải", "Cảm xúc"),
        (597, "doubtful", "adj", "/ˈdaʊt.fəl/", "nghi hoặc, hoài nghi", "Cảm xúc"),
        (598, "down", "adj", "/daʊn/", "nản lòng, chán nản", "Cảm xúc"),
        (599, "drained", "adj", "/dreɪnd/", "kiệt sức", "Cảm xúc"),
        (600, "edgy", "adj", "/ˈedʒ.i/", "cáu kỉnh", "Cảm xúc"),
        (601, "elated", "adj", "/iˈleɪ.t̬ɪd/", "phẩn khởi, hân hoan", "Cảm xúc"),
        (602, "embarrassed", "adj", "/ɪmˈber.əst/", "xấu hổ, ngại ngùng", "Cảm xúc"),
        (603, "empathetic", "adj", "/ˌem.pəˈθet̬.ɪk/", "đồng cảm, xót xa", "Cảm xúc"),
        (604, "engrossed", "adj", "/ɪnˈɡroʊst/", "bị mê hoặc", "Cảm xúc"),
        (605, "enlightened", "adj", "/ɪnˈlaɪ.t̬ənd/", "được làm sáng tỏ, được thông suốt", "Cảm xúc"),
        (606, "envious", "adj", "/ˈen.vi.əs/", "ghen tị, độ kỵ", "Cảm xúc"),
        (607, "excited", "adj", "/ɪkˈsaɪ.t̬ɪd/", "hưng phấn, sôi nổi", "Cảm xúc"),
        (608, "excluded", "adj", "/ɪkˈskluːd/", "bị bỏ rơi, cảm giác lạc lõng", "Cảm xúc"),
        (609, "exhausted", "adj", "/ɪɡˈzɑː.stɪd/", "mệt lử", "Cảm xúc"),
        (610, "flabbergasted", "adj", "/ˈflæb.ɚ.ɡæs.tɪd/", "sửng sốt, thất kinh", "Cảm xúc"),
        (611, "foolish", "adj", "/ˈfuː.lɪʃ/", "dại dột", "Cảm xúc"),
        (612, "frazzled", "adj", "/ˈfræz.əld/", "mệt rã rời, kiệt quệ", "Cảm xúc"),
        (613, "fretful", "adj", "/ˈfret.fəl/", "bực tức, khó chịu", "Cảm xúc"),
        (614, "frustrated", "adj", "/ˈfrʌs.treɪ.t̬ɪd/", "nản lòng, nản chí", "Cảm xúc"),
        (615, "furious", "adj", "/ˈfʊr.i.əs/", "giận dữ, điên tiết", "Cảm xúc"),
        (616, "giddy", "adj", "/ˈɡɪd.i/", "chóng mặt, choáng váng", "Cảm xúc"),
        (617, "glad", "adj", "/ɡlæd/", "vui sướng", "Cảm xúc"),
        (618, "gleeful", "adj", "/ˈɡliː.fəl/", "hân hoan, mừng rỡ", "Cảm xúc"),
        (619, "guarded", "adj", "/ˈɡɑːr.dɪd/", "thận trọng, ý tứ", "Cảm xúc"),
        (620, "guilty", "adj", "/ˈɡɪl.ti/", "mặc cảm, cảm thấy tội lỗi", "Cảm xúc"),
        (621, "hankering", "n", "/ˈhæŋ.kɚ.ɪŋ/", "khao khát, thèm muốn", "Cảm xúc"),
        (622, "hesitant", "adj", "/ˈhez.ə.tənt/", "do dự, ngập ngừng", "Cảm xúc"),
        (623, "hollow", "adj", "/ˈhɑː.loʊ/", "trống rỗng", "Cảm xúc"),
        (624, "horrified", "adj", "/ˈhɔːr.ə.faɪd/", "khiếp sợ", "Cảm xúc"),
        (625, "hostile", "adj", "/ˈhɑː.stəl/", "chống đối, thù địch", "Cảm xúc"),
        (626, "humiliated", "adj", "/hjuːˈmɪl.i.eɪ.t̬ɪd/", "cảm giác bẽ mặt, xấu hổ", "Cảm xúc"),
        (627, "hysterical", "adj", "/hɪˈster.ɪ.kəl/", "kích động, cuồng loạn", "Cảm xúc"),
        (628, "indifferent", "adj", "/ɪnˈdɪf.ɚ.ənt/", "dửng dưng, lãnh đạm, thờ ơ", "Cảm xúc"),
        (629, "indignant", "adj", "/ɪnˈdɪɡ.nənt/", "căm phẫn, phẫn nộ", "Cảm xúc"),
        (630, "intense", "adj", "/ɪnˈtens/", "mãnh liệt, nồng nhiệt", "Cảm xúc"),
        (631, "interested", "adj", "/ˈɪn.trɪ.stɪd/", "hứng thú, thích thú", "Cảm xúc"),
        (632, "intoxicated", "adj", "/ɪnˈtɑːk.sɪ.keɪ.t̬ɪd/", "say sưa", "Cảm xúc"),
        (633, "irritated", "adj", "/ˈɪr.ə.teɪ.t̬ɪd/", "tức tối, khó chịu", "Cảm xúc"),
        (634, "jittery", "adj", "/ˈdʒɪt̬.ɚ.i/", "bồn chồn, dễ bị kích động", "Cảm xúc"),
        (635, "jocular", "adj", "/ˈdʒɑː.kjə.lɚ/", "hài hước, vui vẻ", "Cảm xúc"),
        (636, "jolly", "adj", "/ˈdʒɑː.li/", "vui tươi, nhộn nhịp", "Cảm xúc"),
        (637, "joyful", "adj", "/ˈdʒɔɪ.fəl/", "hân hoan, vui mừng", "Cảm xúc"),
        (638, "jumpy", "adj", "/ˈdʒɔɪ.fəl/", "giật mình, hốt hoảng", "Cảm xúc"),
        (639, "keen", "adj", "/kiːn/", "say mê, ham thích", "Cảm xúc"),
        (640, "lethargic", "adj", "/ləˈθɑːr.dʒɪk/", "mệt mỏi, uể oải", "Cảm xúc"),
        (641, "lonely", "adj", "/ˈloʊn.li/", "cô đơn", "Cảm xúc"),
        (642, "longing", "adj", "/ˈlɑːŋ.ɪŋ/", "thèm khát, thèm muốn", "Cảm xúc"),
        (643, "lost", "adj", "/lɑːst/", "lạc lõng, mất phương hướng", "Cảm xúc"),
        (644, "lucky", "adj", "/ˈlʌk.i/", "may mắn", "Cảm xúc"),
        (645, "melancholic", "adj", "/ˌmel.əŋˈkɑː.lɪk/", "u sầu, buồn bã", "Cảm xúc"),
        (646, "miserable", "adj", "/ˈmɪz.ɚ.ə.bəl/", "khốn khổ, đáng thương", "Cảm xúc"),
        (647, "mortified", "adj", "/ˈmɔːr.t̬ə.faɪd/", "xấu hổ, ái ngại", "Cảm xúc"),
        (648, "mournful", "adj", "/ˈmɔːrn.fəl/", "buồn rầu, ảm đạm", "Cảm xúc"),
        (649, "nasty", "adj", "/ˈnæs.ti/", "tục tĩu", "Cảm xúc"),
        (650, "needy", "adj", "/ˈniː.di/", "thiếu thốn (về mặt tình cảm)", "Cảm xúc"),
        (651, "nervous", "adj", "/ˈnɝː.vəs/", "lo lắng, bồn chồn", "Cảm xúc"),
        (652, "numb", "adj", "/nʌm/", "lặng người", "Cảm xúc"),
        (653, "obsessed", "adj", "/əbˈsest/", "ám ảnh", "Cảm xúc"),
        (654, "offended", "adj", "/əˈfendɪd/", "phật ý, cảm thấy bị xúc phạm", "Cảm xúc"),
        (655, "optimistic", "adj", "/ˌɑːp.təˈmɪs.tɪk/", "lạc quan, yêu đời", "Cảm xúc"),
        (656, "overwhelmed", "adj", "/ˌoʊ.vɚˈwelmd/", "choáng ngợp, quá tải", "Cảm xúc"),
        (657, "paranoid", "adj", "/ˈper.ə.nɔɪd/", "hoang tưởng", "Cảm xúc"),
        (658, "passionate", "adj", "/ˈpæʃ.ən.ət/", "nồng nhiệt, thiết tha", "Cảm xúc"),
        (659, "peaceful", "adj", "/ˈpiːs.fəl/", "thanh thản, bình yên", "Cảm xúc"),
        (660, "perky", "adj", "/ˈpɝː.ki/", "tươi tỉnh, vênh váo", "Cảm xúc"),
        (661, "perplexed", "adj", "/pɚˈplekst/", "lúng túng, bối rối", "Cảm xúc"),
        (662, "pessimistic", "adj", "/ˌpes.əˈmɪs.tɪk/", "bi quan", "Cảm xúc"),
        (663, "petrified", "adj", "/ˈpet.rə.faɪd/", "làm sững sờ, chết điếng", "Cảm xúc"),
        (664, "positive", "adj", "/ˈpɑː.zə.t̬ɪv/", "tích cực, lạc quan", "Cảm xúc"),
        (665, "powerful", "adj", "/ˈpaʊ.ɚ.fəl/", "quyền thế, quyền lực", "Cảm xúc"),
        (666, "proud", "adj", "/praʊd/", "hãnh diện, tự hào", "Cảm xúc"),
        (667, "rattled", "adj", "/ˈræt̬.əld/", "bồn chồn, lo lắng", "Cảm xúc"),
        (668, "reflective", "adj", "/rɪˈflek.tɪv/", "trầm ngâm", "Cảm xúc"),
        (669, "regretful", "adj", "/rɪˈɡret.fəl/", "hối tiếc", "Cảm xúc"),
        (670, "relaxed", "adj", "/rɪˈlækst/", "thư giãn, thoải mái", "Cảm xúc"),
        (671, "relieved", "adj", "/rɪˈliːvd/", "nhẹ nhõm", "Cảm xúc"),
        (672, "remorseful", "adj", "/rɪˈmɔːr.sfəl/", "ăn năn, hối hận", "Cảm xúc"),
        (673, "rueful", "adj", "/ˈruː.fəl/", "buồn bã, rầu rĩ", "Cảm xúc"),
        (674, "satisfied", "adj", "/ˈsæt̬.ɪs.faɪd/", "thỏa mãn, hài lòng", "Cảm xúc"),
        (675, "self-conscious", "adj", "/ˌselfˈkɑːn.ʃəs/", "e dè, ngượng nghịu", "Cảm xúc"),
        (676, "selfish", "adj", "/ˈsel.fɪʃ/", "ích kỷ", "Cảm xúc"),
        (677, "sensitive", "adj", "/ˈsen.sə.t̬ɪv/", "nhạy cảm, dễ tổn thương", "Cảm xúc"),
        (678, "shameful", "adj", "/ˈʃeɪm.fəl/", "đáng hổ thẹn, ngượng", "Cảm xúc"),
        (679, "shock", "adj", "/ʃɑːkt/", "bất ngờ, sốc", "Cảm xúc"),
        (680, "sluggish", "adj", "/ˈslʌɡ.ɪʃ/", "lờ đờ, chậm chạp", "Cảm xúc"),
        (681, "smug", "adj", "/smʌɡ/", "tự mãn", "Cảm xúc"),
        (682, "snappy", "adj", "/ˈsnæp.i/", "dễ gắt gỏng, cáu kỉnh", "Cảm xúc"),
        (683, "somber", "adj", "/ˈsɒm.bər/", "u sầu, ủ rũ", "Cảm xúc"),
        (684, "speechless", "adj", "/ˈspiːtʃ.ləs/", "câm nín", "Cảm xúc"),
        (685, "stressed", "adj", "/strest/", "căng thẳng", "Cảm xúc"),
        (686, "stunned", "adj", "/stʌnd/", "sững sờ, bất ngờ", "Cảm xúc"),
        (687, "submissive", "adj", "/səbˈmɪs.ɪv/", "ngoan ngoãn, dễ bảo", "Cảm xúc"),
        (688, "suffering", "adj", "/səbˈmɪs.ɪv/", "đau đớn, đau khổ", "Cảm xúc"),
        (689, "surprised", "adj", "/sɚˈpraɪzd/", "bất ngờ, ngạc nhiên", "Cảm xúc"),
        (690, "thankful", "adj", "/ˈθæŋk.fəl/", "biết ơn", "Cảm xúc"),
        (691, "thoughtful", "adj", "/ˈθɑːt.fəl/", "trầm ngâm, suy tư", "Cảm xúc"),
        (692, "troubled", "adj", "/ˈtrʌb.əld/", "băn khoăn, lo lắng", "Cảm xúc"),
        (693, "upbeat", "adj", "/ˈʌp.biːt/", "vui vẻ, phấn chấn", "Cảm xúc"),
        (694, "uptight", "adj", "/ˌʌpˈtaɪt/", "căng thẳng, lo lắng", "Cảm xúc"),
        (695, "wary", "adj", "/ˈwer.i/", "thận trọng, đề phòng", "Cảm xúc"),
        (696, "woeful", "adj", "/ˈwoʊ.fəl/", "thiểu não, buồn rầu", "Cảm xúc"),
        (697, "wretched", "adj", "/ˈretʃ.ɪd/", "bất hạnh, đáng thương", "Cảm xúc"),
        (698, "zealous", "adj", "/ˈzel.əs/", "hăng hái, sốt sắng", "Cảm xúc"),
    
        # CHỦ ĐỀ 14: COOKING VERBS - NẤU NƯỚNG (699 - 763)
        (699, "bake", "v", "/beɪk/", "nướng", "Nấu nướng"),
        (700, "barbecue", "v", "/ˈbɑːr.bə.kjuː/", "nướng, quay thịt trên lò", "Nấu nướng"),
        (701, "baste", "v", "/beɪst/", "phết", "Nấu nướng"),
        (702, "blanch", "v", "/blæntʃ/", "chần thức ăn", "Nấu nướng"),
        (703, "blend", "v", "/blend/", "trộn", "Nấu nướng"),
        (704, "boil", "v", "/bɔɪl/", "đun sôi", "Nấu nướng"),
        (705, "braise", "v", "/breɪz/", "om (thịt...)", "Nấu nướng"),
        (706, "brew", "v", "/bruː/", "ủ (trà, rượu...)", "Nấu nướng"),
        (707, "caramelize", "v", "/ˈkɑːr.məl.aɪz/", "thắng đường", "Nấu nướng"),
        (708, "char-broil", "v", "/ˈtʃɑːr.brɔɪl/", "nấu thức ăn trên vỉ nướng", "Nấu nướng"),
        (709, "chill", "v", "/tʃɪl/", "làm tan giá, rã đông", "Nấu nướng"),
        (710, "chop", "v", "/tʃɑːp/", "chặt, bổ", "Nấu nướng"),
        (711, "chunk", "v, n", "/tʃʌŋk/", "cắt khúc, khúc", "Nấu nướng"),
        (712, "churn", "v, n", "/tʃɝːn/", "đánh, khuấy sữa", "Nấu nướng"),
        (713, "coddle", "v", "/ˈkɑː.dəl/", "tần, hầm", "Nấu nướng"),
        (714, "congeal", "v", "/kənˈdʒiːl/", "làm đông, làm cô đặc lại", "Nấu nướng"),
        (715, "cool", "v", "/kuːl/", "để nguội", "Nấu nướng"),
        (716, "deglaze", "v", "/ˌdiːˈɡleɪz/", "làm nước xốt", "Nấu nướng"),
        (717, "descale", "v", "/ˌdiːˈskeɪl/", "cạo cặn", "Nấu nướng"),
        (718, "dice", "v", "/daɪs/", "thái hạt lựu", "Nấu nướng"),
        (719, "dip", "v", "/dɪp/", "nhúng, ngâm", "Nấu nướng"),
        (720, "ferment", "v", "/fɚˈment/", "lên men", "Nấu nướng"),
        (721, "fillet", "v", "/ˈfɪl.ɪt/", "róc xương, lạng thịt", "Nấu nướng"),
        (722, "flambé", "v", "/flɑːmˈbeɪ/", "đốt rượu", "Nấu nướng"),
        (723, "flavor", "v", "/ˈfleɪ.vɚ/", "tẩm gia vị", "Nấu nướng"),
        (724, "fold", "v", "/foʊld/", "quấy, trộn", "Nấu nướng"),
        (725, "garnish", "v", "/ˈɡɑːr.nɪʃ/", "trang trí, bày biện", "Nấu nướng"),
        (726, "knead", "v", "/niːd/", "nhào bột", "Nấu nướng"),
        (727, "layer", "v", "/ˈleɪ.ɚ/", "xếp từng lớp", "Nấu nướng"),
        (728, "leaven", "v", "/ˈlev.ən/", "làm men nở", "Nấu nướng"),
        (729, "marinate", "v", "/ˈmer.ə.neɪt/", "ướp thịt", "Nấu nướng"),
        (730, "mash", "v", "/mæʃ/", "nghiền, làm nát", "Nấu nướng"),
        (731, "measure", "v", "/ˈmeʒ.ɚ/", "cân đếm", "Nấu nướng"),
        (732, "melt", "v", "/melt/", "làm tan chảy", "Nấu nướng"),
        (733, "mince", "v", "/mɪns/", "băm, xay", "Nấu nướng"),
        (734, "pinch", "v", "/pɪntʃ/", "véo", "Nấu nướng"),
        (735, "precook", "v", "/ˌpriːˈkʊk/", "nấu sơ qua", "Nấu nướng"),
        (736, "prepare", "v", "/prɪˈper/", "sơ chế, chuẩn bị", "Nấu nướng"),
        (737, "press", "v", "/pres/", "ấn, ép", "Nấu nướng"),
        (738, "pulp", "v", "/pʌlp/", "nghiền nhão, nghiền nát", "Nấu nướng"),
        (739, "raw", "adj", "/rɑː/", "sống", "Nấu nướng"),
        (740, "refrigerate", "v", "/rɪˈfrɪdʒ.ə.reɪt/", "ướp lạnh", "Nấu nướng"),
        (741, "roast", "v", "/roʊst/", "quay, nướng", "Nấu nướng"),
        (742, "roll", "v", "/roʊl/", "cuộn", "Nấu nướng"),
        (743, "salt", "v", "/sɑːlt/", "ướp gia vị, rắc muối", "Nấu nướng"),
        (744, "saute", "v", "/sɔːˈteɪ/", "rán, áp chảo", "Nấu nướng"),
        (745, "scald", "v", "/skɑːld/", "đun gần sôi", "Nấu nướng"),
        (746, "scramble", "v", "/ˈskræm.bəl/", "trưng (bác) trứng", "Nấu nướng"),
        (747, "shell", "v", "/ʃel/", "bóc vỏ", "Nấu nướng"),
        (748, "shred", "v", "/ʃred/", "xé nhỏ", "Nấu nướng"),
        (749, "shuck", "v", "/ʃʌk/", "bóc vỏ, lột vỏ", "Nấu nướng"),
        (750, "sieve", "v", "/sɪv/", "sàng, rây", "Nấu nướng"),
        (751, "sift", "v", "/sɪft/", "sàng, rắc", "Nấu nướng"),
        (752, "simmer", "v", "/ˈsɪm.ɚ/", "ninh nhỏ lửa", "Nấu nướng"),
        (753, "skewer", "v", "/ˈskjuː.ɚ/", "xiên thịt", "Nấu nướng"),
        (754, "skim", "v", "/skɪm/", "vớt bọt, vớt váng", "Nấu nướng"),
        (755, "slice", "v", "/slaɪs/", "thái", "Nấu nướng"),
        (756, "souse", "v", "/saʊs/", "ngâm, giầm", "Nấu nướng"),
        (757, "sprinkle", "v", "/ˈsprɪŋ.kəl/", "rắc", "Nấu nướng"),
        (758, "steam", "v", "/stiːm/", "hấp", "Nấu nướng"),
        (759, "steep", "v", "/stiːp/", "ngâm vào nước", "Nấu nướng"),
        (760, "stew", "v", "/stuː/", "hầm, ninh nhừ", "Nấu nướng"),
        (761, "stir", "v", "/stɝː/", "xào, quấy", "Nấu nướng"),
        (762, "sweeten", "v", "/ˈswiː.tən/", "làm ngọt", "Nấu nướng"),
        (763, "wash", "v", "/wɑːʃ/", "rửa", "Nấu nướng"),
    
        # CHỦ ĐỀ 15: JOBS AND OCCUPATIONS - NGHỀ NGHIỆP (764 - 797)
        (764, "accountant", "n", "/əˈkaʊn.t̬ənt/", "kế toán", "Nghề nghiệp"),
        (765, "actor/ actress", "n", "/ˈæk.tɚ/ /ˈæk.trəs/", "diễn viên", "Nghề nghiệp"),
        (766, "artist", "n", "/ˈɑːr.t̬ɪst/", "nghệ sỹ", "Nghề nghiệp"),
        (767, "astronaut", "n", "/ˈæs.trə.nɑːt/", "phi hành gia", "Nghề nghiệp"),
        (768, "baker", "n", "/ˈbeɪ.kɚ/", "thợ nướng bánh", "Nghề nghiệp"),
        (769, "bellboy", "n", "/ˈbel.bɔɪ/", "nhân viên hành lý", "Nghề nghiệp"),
        (770, "bishop", "n", "/ˈbɪʃ.əp/", "giám mục", "Nghề nghiệp"),
        (771, "butcher", "n", "/ˈbʊtʃ.ɚ/", "người mổ thịt", "Nghề nghiệp"),
        (772, "cashier", "n", "/kæʃˈɪr/", "nhân viên thu ngân", "Nghề nghiệp"),
        (773, "chef", "n", "/ʃef/", "đầu bếp", "Nghề nghiệp"),
        (774, "customs officer", "n", "/ˈkʌs·təmz ˈɑː.fɪ.sɚ/", "nhân viên hải quan", "Nghề nghiệp"),
        (775, "delivery man", "n", "/dɪˈlɪv.ɚ.i.mæn/", "nhân viên giao hàng", "Nghề nghiệp"),
        (776, "entrepreneur", "n", "/ˌɑːn.trə.prəˈnɝː/", "nhà kinh doanh", "Nghề nghiệp"),
        (777, "factory worker", "n", "/ˈfæk.tɚ.i ˈwɝː.kɚ/", "công nhân nhà máy", "Nghề nghiệp"),
        (778, "florist", "n", "/ˈflɔːr.ɪst/", "người bán hoa", "Nghề nghiệp"),
        (779, "hairdresser", "n", "/ˈherˌdres.ɚ/", "thợ cắt tóc", "Nghề nghiệp"),
        (780, "judge", "n", "/dʒʌdʒ/", "thẩm phán", "Nghề nghiệp"),
        (781, "lawyer", "n", "/ˈlɑː.jɚ/", "luật sư", "Nghề nghiệp"),
        (782, "miner", "n", "/ˈmaɪ.nɚ/", "thợ mỏ", "Nghề nghiệp"),
        (783, "musician", "n", "/mjuːˈzɪʃ.ən/", "nhạc sĩ, nhà soạn nhạc", "Nghề nghiệp"),
        (784, "optician", "n", "/ɑːpˈtɪʃ.ən/", "chuyên gia nhãn khoa", "Nghề nghiệp"),
        (785, "pharmacist", "n", "/ˈfɑːr.mə.sɪst/", "dược sĩ", "Nghề nghiệp"),
        (786, "plumber", "n", "/ˈplʌm.ɚ/", "thợ ống nước", "Nghề nghiệp"),
        (787, "politician", "n", "/ˌpɑː.ləˈtɪʃ.ən/", "chính trị gia", "Nghề nghiệp"),
        (788, "programmer", "n", "/ˈproʊ.ɡræm.ɚ/", "lập trình viên", "Nghề nghiệp"),
        (789, "real estate agent", "n", "/ˈriː.əl ɪ.steɪt ˌeɪ.dʒənt/", "người môi giới bất động sản", "Nghề nghiệp"),
        (790, "receptionist", "n", "/rɪˈsep.ʃən.ɪst/", "nhân viên lễ tân, tiếp tân", "Nghề nghiệp"),
        (791, "speaker", "n", "/ˈspiː.kɚ/", "diễn giả", "Nghề nghiệp"),
        (792, "street vendor", "n", "/striːt ˈven.dɚ/", "người bán hàng trên đường, bán hàng rong", "Nghề nghiệp"),
        (793, "tailor", "n", "/ˈteɪ.lɚ/", "thợ may", "Nghề nghiệp"),
        (794, "taxi driver", "n", "/ˈtæk.si ˌdraɪ.vɚ/", "tài xế xe taxi", "Nghề nghiệp"),
        (795, "teacher", "n", "/ˈtiː.tʃɚ/", "giáo viên", "Nghề nghiệp"),
        (796, "veterinarian", "n", "/ˌvet.ər.ɪˈner.i.ən/", "bác sỹ thú y", "Nghề nghiệp"),
        (797, "writer", "n", "/ˈraɪ.t̬ɚ/", "người viết sách", "Nghề nghiệp"),
    
        # CHỦ ĐỀ 16: COLORS AND SHAPES - MÀU SẮC VÀ HÌNH DẠNG (798 - 860)
        (798, "yellow", "n, adj", "/ˈjel.oʊ/", "màu vàng", "Màu sắc & Hình dạng"),
        (799, "white", "n, adj", "/waɪt/", "màu trắng", "Màu sắc & Hình dạng"),
        (800, "wheat", "n, adj", "/wiːt/", "màu vàng đất", "Màu sắc & Hình dạng"),
        (801, "teal", "n, adj", "/tiːl/", "màu xanh mòng két (xanh lam pha xanh lục đậm)", "Màu sắc & Hình dạng"),
        (802, "silver", "n, adj", "/ˈsɪl.vɚ/", "màu bạc", "Màu sắc & Hình dạng"),
        (803, "sanguine", "n, adj", "/ˈsæŋ.ɡwɪn/", "đỏ thẫm (như máu)", "Màu sắc & Hình dạng"),
        (804, "red", "n, adj", "/red/", "màu đỏ", "Màu sắc & Hình dạng"),
        (805, "purple", "n, adj", "/ˈpɝː.pəl/", "màu tím", "Màu sắc & Hình dạng"),
        (806, "orange", "n, adj", "/ˈɔːr.ɪndʒ/", "màu cam", "Màu sắc & Hình dạng"),
        (807, "navy (blue)", "n, adj", "/ˈneɪ·vi (ˈblu)/", "màu xanh tím than", "Màu sắc & Hình dạng"),
        (808, "maroon", "n, adj", "/məˈruːn/", "màu nâu sẫm, màu hạt dẻ", "Màu sắc & Hình dạng"),
        (809, "magenta", "n, adj", "/məˈdʒen.tə/", "màu hồng sẫm", "Màu sắc & Hình dạng"),
        (810, "ivory", "n, adj", "/ˈaɪ.vɚ.i/", "màu trắng ngà", "Màu sắc & Hình dạng"),
        (811, "indigo", "n, adj", "/ˈɪn.dɪ.ɡoʊ/", "màu chàm", "Màu sắc & Hình dạng"),
        (812, "green", "n, adj", "/ɡriːn/", "xanh dương, xanh lá cây", "Màu sắc & Hình dạng"),
        (813, "gray", "n, adj", "/ɡreɪ/", "màu xám", "Màu sắc & Hình dạng"),
        (814, "fuchsia", "n, adj", "/ˈfjuː.ʃə/", "màu hồng hoa Vân Anh", "Màu sắc & Hình dạng"),
        (815, "cyan", "n, adj", "/ˈsaɪ.ən/", "màu xanh lơ", "Màu sắc & Hình dạng"),
        (816, "crimson", "n, adj", "/ˈkrɪm.zən/", "màu đỏ thẫm", "Màu sắc & Hình dạng"),
        (817, "coral", "n, adj", "/ˈkɔːr.əl/", "màu hồng san hô", "Màu sắc & Hình dạng"),
        (818, "charcoal", "n, adj", "/ˈtʃɑːr.koʊl/", "màu than chì", "Màu sắc & Hình dạng"),
        (819, "burgundy", "n, adj", "/ˈbɝː.ɡən.di/", "màu đỏ rượu, đỏ tía", "Màu sắc & Hình dạng"),
        (820, "brown", "n, adj", "/braʊn/", "màu nâu", "Màu sắc & Hình dạng"),
        (821, "blue", "n, adj", "/bluː/", "màu xanh lam, xanh nước biển", "Màu sắc & Hình dạng"),
        (822, "blond", "n, adj", "/blɑnd/", "vàng hoe", "Màu sắc & Hình dạng"),
        (823, "black", "n, adj", "/blæk/", "màu đen", "Màu sắc & Hình dạng"),
        (824, "beige", "n, adj", "/beɪʒ/", "màu be", "Màu sắc & Hình dạng"),
        (825, "azure", "n, adj", "/ˈæʒ.ɚ/", "màu xanh da trời, xanh ngắt", "Màu sắc & Hình dạng"),
        (826, "aquamarine", "n, adj", "/ˌæk.wə.məˈriːn/", "màu xanh ngọc", "Màu sắc & Hình dạng"),
        (827, "arrow", "n", "/ˈer.oʊ/", "hình mũi tên", "Màu sắc & Hình dạng"),
        (828, "circle", "n", "/ˈsɝː.kəl/", "đường tròn", "Màu sắc & Hình dạng"),
        (829, "cone", "n", "/koʊn/", "hình nón", "Màu sắc & Hình dạng"),
        (830, "crescent", "n", "/ˈkres.ənt/", "hình lưỡi liềm", "Màu sắc & Hình dạng"),
        (831, "cross", "n", "/krɑːs/", "hình chữ thập", "Màu sắc & Hình dạng"),
        (832, "cube", "n", "/kjuːb/", "hình lập phương, hình khối", "Màu sắc & Hình dạng"),
        (833, "curve", "n", "/wedʒ/", "đường cong", "Màu sắc & Hình dạng"),
        (834, "cylinder", "n", "/ˈsɪl.ɪn.dɚ/", "hình trụ", "Màu sắc & Hình dạng"),
        (835, "decagon", "n", "/ˈdek.ə.ɡɑːn/", "hình mười cạnh", "Màu sắc & Hình dạng"),
        (836, "diamond", "n", "/ˈdaɪ.ə.mənd/", "hình kim cương", "Màu sắc & Hình dạng"),
        (837, "ellipse", "n", "/iˈlɪps/", "hình Elip", "Màu sắc & Hình dạng"),
        (838, "equilateral triangle", "n", "/ˌi·kwəˈlæt̬·ə·rəl ˈtrɑɪˌæŋ·ɡəl/", "tam giác đều", "Màu sắc & Hình dạng"),
        (839, "heart", "n", "/hɑːrt/", "hình trái tim", "Màu sắc & Hình dạng"),
        (840, "heptagon", "n", "/ˈhep.tə.ɡɑːn/", "hình bảy cạnh", "Màu sắc & Hình dạng"),
        (841, "hexagon", "n", "/ˈhek.sə.ɡɑːn/", "hình lục giác (sáu cạnh)", "Màu sắc & Hình dạng"),
        (842, "isosceles triangle", "n", "/aɪˌsɑː.səl.iːz ˈtraɪ.æŋ. ɡəl/", "tam giác cân", "Màu sắc & Hình dạng"),
        (843, "nonagon", "n", "/ˈɑːk.tə.ɡɑːn/", "hình cửu giác (chín cạnh)", "Màu sắc & Hình dạng"),
        (844, "octagon", "n", "/ˈɑːk.tə.ɡɑːn/", "hình bát giác", "Màu sắc & Hình dạng"),
        (845, "orb", "n", "/ɔːrb/", "hình cầu, quả cầu", "Màu sắc & Hình dạng"),
        (846, "oval", "n", "/ˈoʊ.vəl/", "hình trái xoan, hình bầu dục", "Màu sắc & Hình dạng"),
        (847, "parallelogram", "n", "/ˌper.əˈlel.ə.ɡræm/", "hình bình hành", "Màu sắc & Hình dạng"),
        (848, "pentagon", "n", "/ˈpen.tə.ɡən/", "hình ngũ giác (năm cạnh)", "Màu sắc & Hình dạng"),
        (849, "pyramid", "n", "/ˈpɪr.ə.mɪd/", "hình chóp", "Màu sắc & Hình dạng"),
        (850, "rectangle", "n", "/ˈrek.tæŋ.ɡəl/", "hình chữ nhật", "Màu sắc & Hình dạng"),
        (851, "rhombus", "n", "/ˈrɑːm.baɪ/", "hình thoi", "Màu sắc & Hình dạng"),
        (852, "right-angled triangle", "n", "/ˌraɪt.æŋ.ɡəld ˈtraɪ.æŋ. ɡəl/", "tam giác vuông", "Màu sắc & Hình dạng"),
        (853, "scalene triangle", "n", "/ˌskeɪ.liːn ˈtraɪ.æŋ.ɡəl/", "tam giác thường", "Màu sắc & Hình dạng"),
        (854, "semicircle", "n", "/ˈsem.iˌsɝː.kəl/", "hình bán cầu", "Màu sắc & Hình dạng"),
        (855, "sphere", "n", "/sfɪr/", "hình cầu, khối cầu", "Màu sắc & Hình dạng"),
        (856, "square", "n", "/skwer/", "hình vuông", "Màu sắc & Hình dạng"),
        (857, "star", "n", "/stɑːr/", "hình ngôi sao", "Màu sắc & Hình dạng"),
        (858, "trapezoid", "n", "/ˈtræp.ɪ.zɔɪd/", "hình thang", "Màu sắc & Hình dạng"),
        (859, "triangle", "n", "/ˈtraɪ.æŋ.ɡəl/", "hình tam giác", "Màu sắc & Hình dạng"),
        (860, "wedge", "n", "/wedʒ/", "hình chữ V", "Màu sắc & Hình dạng"),
    
        # CHỦ ĐỀ 17: VEHICLES - PHƯƠNG TIỆN GIAO THÔNG (861 - 896)
        (861, "aerial", "adj", "/ˈer.i.əl/", "trên không", "Phương tiện giao thông"),
        (862, "aerial tramway", "n", "/ˈer.i.əl ˈtræm.weɪ/", "cáp treo", "Phương tiện giao thông"),
        (863, "airplane", "n", "/ˈer.pleɪn/", "máy bay", "Phương tiện giao thông"),
        (864, "ambulance", "n", "/ˈæm.bjə.ləns/", "xe cứu thương", "Phương tiện giao thông"),
        (865, "automobile", "n", "/ˈɑː.t̬ə.moʊ.biːl/", "xe ô tô", "Phương tiện giao thông"),
        (866, "baby carriage", "n", "/ˈbeɪ.bi ˌker.ɪdʒ/", "xe đẩy trẻ con", "Phương tiện giao thông"),
        (867, "bicycle", "n", "/ˈbaɪ.sə.kəl/", "xe đạp", "Phương tiện giao thông"),
        (868, "boat", "n", "/boʊt/", "tàu thuyền", "Phương tiện giao thông"),
        (869, "bus", "n", "/bʌs/", "xe buýt", "Phương tiện giao thông"),
        (870, "carriage", "n", "/ˈker.ɪdʒ/", "xe ngựa", "Phương tiện giao thông"),
        (871, "cement mixer", "n", "/sɪˈment ˌmɪk.sɚ/", "máy trộn xi măng", "Phương tiện giao thông"),
        (872, "crane", "n", "/kreɪn/", "cần cẩu, cần trục", "Phương tiện giao thông"),
        (873, "dump truck", "n", "/ˈdʌmp ˌtrʌk/", "xe tải tự đổ", "Phương tiện giao thông"),
        (874, "emergency brake", "n", "/ɪˈmɝː.dʒən.si ˌbreɪk/", "thắng tay khẩn cấp", "Phương tiện giao thông"),
        (875, "fire engine", "n", "/ˈfaɪr ˌen.dʒɪn/", "xe cứu hỏa", "Phương tiện giao thông"),
        (876, "forklift", "n", "/ˈfɔrkˌlift/", "xe nâng", "Phương tiện giao thông"),
        (877, "helicopter", "n", "/ˈhel.əˌkɑːp.tɚ/", "trực thăng", "Phương tiện giao thông"),
        (878, "motorcycle", "n", "/ˈmoʊ.t̬ɚˌsaɪ.kəl/", "xe mô tô", "Phương tiện giao thông"),
        (879, "mountain bike", "n", "/ˈmaʊn.tən ˌbaɪk/", "xe đạp leo núi", "Phương tiện giao thông"),
        (880, "police car", "n", "/pəˈliːs ˌkɑːr/", "xe cảnh sát", "Phương tiện giao thông"),
        (881, "propeller", "n", "/prəˈpel.ɚ/", "chân vịt, máy đẩy", "Phương tiện giao thông"),
        (882, "rearview mirror", "n", "/ˌrɪr.vju ˈmɪr.ɚ/", "gương chiếu hậu", "Phương tiện giao thông"),
        (883, "rowboat", "n", "/ˈroʊ ˌboʊt/", "thuyền có mái chèo", "Phương tiện giao thông"),
        (884, "scooter", "n", "/ˈskuː.t̬ɚ/", "xe máy tay ga", "Phương tiện giao thông"),
        (885, "seat belt", "n", "/ˈsiːt ˌbelt/", "dây đai an toàn", "Phương tiện giao thông"),
        (886, "skateboard", "n", "/ˈskeɪt.bɔːrd/", "ván trượt", "Phương tiện giao thông"),
        (887, "streetcar", "n", "/ˈstriːt.kɑːr/", "xe điện", "Phương tiện giao thông"),
        (888, "subway", "n", "/ˈsʌb.weɪ/", "đường ngầm", "Phương tiện giao thông"),
        (889, "taxi", "n", "/ˈtæk.si/", "xe taxi", "Phương tiện giao thông"),
        (890, "tractor", "n", "/ˈtræk.tɚ/", "máy kéo", "Phương tiện giao thông"),
        (891, "train", "n", "/treɪn/", "tàu hỏa", "Phương tiện giao thông"),
        (892, "tramway", "n", "/ˈtræm.weɪ/", "đường tàu điện", "Phương tiện giao thông"),
        (893, "van", "n", "/væn/", "xe tải", "Phương tiện giao thông"),
        (894, "vehicle", "n", "/ˈviː.ə.kəl/", "phương tiện giao thông", "Phương tiện giao thông"),
        (895, "windscreen wiper", "n", "/ˈwɪnd.skriːn ˌwaɪ.pɚ/", "cần gạt nước", "Phương tiện giao thông"),
    
        # CHỦ ĐỀ 18: TRAVEL - DU LỊCH (897 - 914)
        (896, "airport", "n", "/ˈer.pɔːrt/", "sân bay", "Du lịch"),
        (897, "arrive", "v", "/əˈraɪv/", "đến nơi", "Du lịch"),
        (898, "check-in", "n", "/tʃek ɪn/", "đăng ký phòng ở khách sạn", "Du lịch"),
        (899, "cruise", "n", "/kruːz/", "chuyến đi chơi trên biển", "Du lịch"),
        (900, "depart", "v", "/dɪˈpɑːrt/", "khởi hành", "Du lịch"),
        (901, "destination", "n", "/ˌdes.təˈneɪ.ʃən/", "điểm đến", "Du lịch"),
        (902, "expedition", "n", "/ˌek.spəˈdɪʃ.ən/", "cuộc thám hiểm", "Du lịch"),
        (903, "journey", "n", "/ˈdʒɝː.ni/", "hành trình", "Du lịch"),
        (904, "land", "v", "/lænd/", "hạ cánh", "Du lịch"),
        (905, "leave", "v", "/liːv/", "rời đi", "Du lịch"),
        (906, "passenger", "n", "/ˈpæs.ən.dʒɚ/", "hành khách", "Du lịch"),
        (907, "route", "n", "/ruːt/ /raʊt/", "lộ trình, hành trình", "Du lịch"),
        (908, "safari", "n", "/səˈfɑːr.i/", "cuộc đi săn", "Du lịch"),
        (909, "tour", "n", "/tʊr/", "chuyến đi du lịch", "Du lịch"),
        (910, "travel", "v", "/ˈtræv.əl/", "đi du lịch", "Du lịch"),
        (911, "trip", "n", "/trɪp/", "cuộc du ngoạn, dạo chơi", "Du lịch"),
        (912, "visit", "v", "/ˈvɪz.ɪt/", "thăm viếng", "Du lịch"),
        (913, "voyage", "n", "/ˈvɔɪ.ɪdʒ/", "chuyến du lịch dài ngày", "Du lịch"),
    
        # CHỦ ĐỀ 19: FAMILY - GIA ĐÌNH (915 - 1000)
        (914, "ancestor", "n", "/ˈæn.ses.tɚ/", "tổ tiên", "Gia đình"),
        (915, "aunt", "n", "/ænt/", "cô, dì", "Gia đình"),
        (916, "bachelor", "n", "/ˈbætʃ.əl.ɚ/", "trai tân, người chưa vợ", "Gia đình"),
        (917, "birth mother", "n", "/ˈbɝːθ ˌmʌð.ɚ/", "mẹ đẻ", "Gia đình"),
        (918, "blood relative", "n", "/ˌblʌd ˈrel.ə.tɪv/", "quan hệ máu mủ", "Gia đình"),
        (919, "bride", "n", "/braɪd/", "cô dâu", "Gia đình"),
        (920, "bridegroom", "n", "/ˈbraɪd.ɡruːm/", "chú rể", "Gia đình"),
        (921, "brother", "n", "/ˈbrʌð.ɚ/", "anh, em trai", "Gia đình"),
        (922, "brother-in-law", "n", "/ˈbrʌð.ɚ.ɪn.lɑː/", "anh (em) rể, anh (em) vợ", "Gia đình"),
        (923, "brotherhood", "n", "/ˈbrʌð.ɚ.hʊd/", "tình anh em, huynh đệ", "Gia đình"),
        (924, "brotherly", "adj, adv", "/ˈbrʌð.ɚ.li/", "thân thiết như anh em", "Gia đình"),
        (925, "care-giver", "n", "/ˈkerˌɡɪv.ɚ/", "điều dưỡng viên", "Gia đình"),
        (926, "child", "n", "/tʃaɪld/", "con", "Gia đình"),
        (927, "childhood", "n", "/ˈtʃaɪld.hʊd/", "tuổi thơ", "Gia đình"),
        (928, "children", "n", "/ˈtʃɪl.drən/", "những đứa con", "Gia đình"),
        (929, "clan", "n", "/klæn/", "thị tộc, gia tộc", "Gia đình"),
        (930, "close-knit", "adj", "/ˌkloʊsˈnɪt/", "gắn bó khăng khít", "Gia đình"),
        (931, "connection", "n", "/kəˈnek.ʃən/", "mối quan hệ", "Gia đình"),
        (932, "cousin", "n", "/ˈkʌz.ən/", "anh em họ", "Gia đình"),
        (933, "dad", "n", "/dæd/", "bố", "Gia đình"),
        (934, "daughter", "n", "/ˈdɑː.t̬ɚ/", "con gái (quan hệ với bố mẹ)", "Gia đình"),
        (935, "daughter-in-law", "n", "/ˈdɑː.t̬ɚ.ɪn.lɑː/", "con dâu", "Gia đình"),
        (936, "descendant", "n", "/dɪˈsen.dənt/", "con cháu, hậu duệ", "Gia đình"),
        (937, "devoted", "adj", "/dɪˈvoʊ.t̬ɪd/", "tận tâm, tận tụy", "Gia đình"),
        (938, "divorce", "n, v", "/dɪˈvɔːrs/", "li dị", "Gia đình"),
        (939, "eligible", "adj", "/ˈel.ə.dʒə.bəl/", "đủ tư cách", "Gia đình"),
        (940, "engaged", "adj", "/ɪnˈɡeɪdʒd/", "đính ước, hứa hôn", "Gia đình"),
        (941, "engagement", "n", "/ɪnˈɡeɪdʒ.mənt/", "sự hẹn ước, hứa hôn", "Gia đình"),
        (942, "estranged", "adj", "/ɪˈstreɪndʒd/", "ly thân", "Gia đình"),
        (943, "ex-husband", "n", "/ˌeksˈhʌz.bənd/", "chồng cũ", "Gia đình"),
        (944, "ex-wife", "n", "/ˌeksˈwaɪf/", "vợ cũ", "Gia đình"),
        (945, "extended family", "n", "/ɪkˌsten.dɪd ˈfæm.əl.i/", "đại gia đình", "Gia đình"),
        (946, "family", "n", "/ˈfæm.əl.i/", "gia đình", "Gia đình"),
        (947, "family tree", "n", "/ˌfæm.əl.i ˈtriː/", "cây phả hệ", "Gia đình"),
        (948, "father", "n", "/ˈfɑː.ðɚ/", "bố, cha", "Gia đình"),
        (949, "father-in-law", "n", "/ˈfɑː.ðɚ.ɪn.lɑː/", "bố vợ, bố chồng", "Gia đình"),
        (950, "fiancée", "n", "/ˌfiː.ɑːnˈseɪ/", "hôn thê, vợ chưa cưới", "Gia đình"),
        (951, "first born", "adj, n", "/ˈfɝːst.bɔːrn/", "đầu lòng, con đầu lòng", "Gia đình"),
        (952, "first cousin", "n", "/ˌfɝːst ˈkʌz.ən/", "anh, chị, em họ ruột", "Gia đình"),
        (953, "flesh and blood", "n", "/ˈfleʃ ən ˈblʌd/", "người thân, gia đình máu mủ", "Gia đình"),
        (954, "folks", "n", "/foʊks/", "người thân thuộc", "Gia đình"),
        (955, "foster", "v", "/ˈfɑː.stɚ/", "nuôi dưỡng, nuôi nấng", "Gia đình"),
        (956, "foster child", "n", "/ˈfɑː.stɚ tʃaɪld/", "con nuôi", "Gia đình"),
        (957, "foster father", "n", "/ˈfɑː.stɚ fɑː.ðɚ/", "cha nuôi", "Gia đình"),
        (958, "foster mother", "n", "/ˈfɑː.stɚˈmʌð.ɚ/", "mẹ nuôi", "Gia đình"),
        (959, "fraternal", "adj", "/frəˈtɝː.nəl/", "(thuộc) anh em", "Gia đình"),
        (960, "friend", "n", "/frend/", "bạn bè", "Gia đình"),
        (961, "genealogy", "n", "/ˌdʒiː.niˈæl.ə.dʒi/", "bảng phả hệ", "Gia đình"),
        (962, "grandchild", "n", "/ˈɡræn.tʃaɪld/", "cháu", "Gia đình"),
        (963, "grandfather", "n", "/ˈɡræn.fɑː.ðɚ/", "ông nội (ngoại)", "Gia đình"),
        (964, "grandmother", "n", "/ˈɡræn.mʌð.ɚ/", "bà nội (ngoại)", "Gia đình"),
        (965, "grandparent", "n", "/ˈɡræn.per.ənt/", "ông (bà)", "Gia đình"),
        (966, "granny", "n", "/ˈɡræn.i/", "bà nội (ngoại)", "Gia đình"),
        (967, "great-aunt", "n", "/ˌɡreɪt ˈænt/", "bà cô, bà bác", "Gia đình"),
        (968, "great-granddaughter", "n", "/ˌɡreɪtˈɡræn.dɑː.t̬ɚ/", "chắt gái", "Gia đình"),
        (969, "great-grandfather", "n", "/ˌɡreɪtˈɡræn.fɑː.ðɚ/", "ông cố, cụ ông", "Gia đình"),
        (970, "great-grandmother", "n", "/ˌɡreɪtˈɡræm.mʌð.ər/", "bà cố, cụ bà", "Gia đình"),
        (971, "great-grandparent", "n", "/ˌɡreɪtˈɡræn.per.ənt/", "ông (bà) cố", "Gia đình"),
        (972, "great-grandson", "n", "/ˌɡreɪtˈɡræn.sʌn/", "chắt trai", "Gia đình"),
        (973, "great-uncle", "n", "/ˌɡreɪt ˈʌŋ.kəl/", "ông (bà) trẻ", "Gia đình"),
        (974, "groom", "n", "/ɡruːm/ /ɡrʊm/", "chú rể", "Gia đình"),
        (975, "grown-up", "n, adj", "/ˌɡroʊn ˈʌp/", "người lớn, người trưởng thành; đã trưởng thành", "Gia đình"),
        (976, "half-brother", "n", "/ˈhæfˌbrʌð.ɚ/", "anh (em) cùng cha khác mẹ, anh (em) cùng mẹ khác cha", "Gia đình"),
        (977, "half-sister", "n", "/ˈhæfˌsɪs.tɚ/", "chị (em) cùng cha khác mẹ, chị (em) cùng mẹ khác cha", "Gia đình"),
        (978, "heir", "n", "/er/", "người thừa kế (nam)", "Gia đình"),
        (979, "heiress", "n", "/ˈer.es/", "người thừa kế (nữ)", "Gia đình"),
        (980, "helpmate", "n", "/ˈhelpmeɪt/", "bạn đời", "Gia đình"),
        (981, "hereditary", "adj", "/həˈred.ə.ter.i/", "di truyền", "Gia đình"),
        (982, "heritage", "n", "/ˈher.ɪ.t̬ɪdʒ/", "tài sản thừa kế, di sản", "Gia đình"),
        (983, "history", "n", "/ˈhɪs.t̬ɚ.i/", "lịch sử gia đình", "Gia đình"),
        (984, "home", "n", "/hoʊm/", "nhà, gia đình", "Gia đình"),
        (985, "household", "n", "/ˈhaʊs.hoʊld/", "hộ gia đình", "Gia đình"),
        (986, "husband", "n", "/ˈhʌz.bənd/", "chồng", "Gia đình"),
        (987, "identical twin", "n", "/aɪˌden.t̬ə.kəl ˈtwɪn/", "sinh đôi giống hệt", "Gia đình"),
        (988, "in-law", "adj", "/ˈɪn.lɑː/", "bố (mẹ) chồng bố (mẹ) vợ", "Gia đình"),
        (989, "infancy", "n", "/ˈɪn.fən.si/", "tuổi bế ẵm, tuổi thơ bé", "Gia đình"),
        (990, "infant", "n, adj", "/ˈɪn.fənt/", "đứa bé sơ sinh", "Gia đình"),
        (991, "inherit", "v", "/ɪnˈher.ɪt/", "thừa hưởng, thừa kế", "Gia đình"),
        (992, "inheritance", "n", "/ɪnˈher.ɪ.təns/", "sự thừa kế, của thừa kế", "Gia đình"),
        (993, "juvenile", "n, adj", "/ˈdʒuː.və.nəl/", "người chưa đến tuổi trưởng thành, vị thành niên", "Gia đình"),
        (994, "kin", "n, adj", "/kɪn/", "dòng họ, gia đình", "Gia đình"),
        (995, "kindred", "n, adj", "/ˈkɪn.drəd/", "họ hàng thân thích", "Gia đình"),
        (996, "kinfolk", "n", "/ˈkɪn.foʊk/", "người thân, họ hàng", "Gia đình"),
        (997, "kinship", "n", "/ˈkɪn.ʃɪp/", "tình thân", "Gia đình"),
        (998, "kith", "n", "/ˌkɪθ ən ˈkɪn/", "họ hàng gia đình", "Gia đình"),
        (999, "lineage", "n", "/ˈlɪn.i.ɪdʒ/", "nòi giống, dòng dõi", "Gia đình"),
]

st.title("🎯 Ứng Dụng Học Từ Vựng Tiếng Anh")

# 1. Khởi tạo bài học
if "selected_words" not in st.session_state:
    # Lấy ngẫu nhiên các từ từ danh sách để đố
  st.session_state.selected_words = random.sample(VOCAB_LIST, len(VOCAB_LIST))

  st.session_state.current_index = 0
  st.session_state.score = 0
  st.session_state.answered = False

# # 2. Kiểm tra xem còn câu hỏi không
if st.session_state.current_index < len(st.session_state.selected_words):
    idx = st.session_state.current_index
    word_info = st.session_state.selected_words[idx]
    stt, english_word, word_type, phonetic, vietnamese_meaning, topic_name = word_info


    # Hiển thị câu hỏi giống giao diện Terminal cũ của bạn
    st.subheader(f"📝 Câu {idx + 1}/{len(st.session_state.selected_words)}")
    st.info(f"👉 **Loại từ:** {word_type} | **Phiên âm:** {phonetic}")
    st.markdown(f"### Từ tiếng Việt: **>> {vietnamese_meaning} <<**")

    # Ô nhập đáp án
    user_input = st.text_input("Nhập từ tiếng Anh của bạn:", key=f"input_{idx}")

    # Nút kiểm tra
    if st.button("Kiểm tra đáp án", key=f"btn_{idx}"):
        st.session_state.answered = True
        if user_input.strip().lower() == english_word.strip().lower():
            st.success(f"🎉 CHÍNH XÁC! Từ đúng là: **{english_word}**")
            st.session_state.score += 1
        else:
            st.error(f"❌ SAI RỒI! Đáp án đúng phải là: **{english_word}**")

    # Nút chuyển câu
    if st.session_state.answered:
        if st.button("Câu tiếp theo ➡️"):
            st.session_state.current_index += 1
            st.session_state.answered = False
            st.rerun()
else:
    st.balloons() # Hiệu ứng bóng bay chúc mừng khi thắng cuộc
    st.success(f"🏆 Hoàn thành! Điểm số: {st.session_state.score}/{len(st.session_state.selected_words)}")
    if st.button("Làm lại bài mới 🔄"):
        del st.session_state.selected_words
        st.rerun()
